//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ElementData.rc
//
#define ID_RETURN                       2
#define IDC_ADD_OPERATION               3
#define IDC_ADD                         3
#define ID_DEL_ITEM                     3
#define ID_SET_TO_NULL                  3
#define IDC_DEL_OPERATION               4
#define IDC_DEL                         4
#define ID_EXPORT                       4
#define IDC_MOVE_UP                     5
#define IDC_EXPORT                      5
#define IDC_DEL_ALL                     5
#define ID_CHECK_OUT                    5
#define IDC_MOVE_DOWN                   6
#define ID_FRESH_TREASURE               6
#define IDC_TREASURE_MOVE_UP            7
#define IDC_ADD_CONDITION               8
#define ID_CHECK_IN                     8
#define ID_ADD_ITEM                     9
#define IDC_TREASURE_MOVE_DOWN          10
#define IDD_ABOUTBOX                    100
#define IDD_ELEMENTDATA_FORM            101
#define IDD_COMMONFILE_DIALOG           102
#define IDR_MAINFRAME                   128
#define IDR_ELEMENTYPE                  129
#define IDD_TEMPLATE_NEW                130
#define IDD_DIALOG_LIST_BAR             131
#define IDI_FOLDER                      133
#define IDI_OBJECT                      134
#define IDD_DIALOG_LIST                 135
#define IDR_MENU_CREATE_OBJECT          136
#define IDD_TEMPLATE_DLG                137
#define IDD_DIALOG_TEMPLATE_CREATE      138
#define IDD_DIALOG_EXT_CREATE           139
#define IDD_DIALOG_OPTION_VSS           140
#define IDI_WRITEABLE                   141
#define IDD_TEMPL_ID_SEL                142
#define IDD_FACTIONS_SEL                143
#define IDD_DIALOG_LOGO                 144
#define IDB_LISTTAG                     146
#define IDD_EQUIP_MASK                  148
#define IDD_TALK_DIALOG                 149
#define IDD_DIALOG_CREATE_WINDOW        150
#define IDD_NEW_TALK_FILE               151
#define IDR_MENU_TALK                   152
#define IDB_TALKLIST                    153
#define IDC_NODRAG                      154
#define IDD_DIALOG_TEST                 155
#define IDD_TEXT_INPUT                  156
#define IDD_WIPE_OFF                    157
#define IDD_PASSWORD                    158
#define IDD_SINGLE_TEXT                 159
#define IDD_DIALOG_POLICY               160
#define IDR_MENU_POLICY                 161
#define IDD_DIALOG_POLICY_TRIGGER       162
#define IDD_DIALOG_POLICY_OPERATION     163
#define IDD_DIALOG_CONDITION            164
#define IDD_DIALOG_POLICY_CREATE        165
#define IDD_DIALOG_MOUNSTER_FALL_LIST   166
#define IDD_DIALOG_MOUNSTER_FALL_ITEM   167
#define IDD_DIALOG_MOUNSTER_ELEMENT     168
#define IDD_TEMPL_ID_SEL_EX             169
#define IDD_DIALOG_EXT_SEL              170
#define IDD_DIALOG_TREASURE             172
#define IDD_DIALOG_TREASURE_ITEM        173
#define IDD_DIALOG_TIME                 174
#define IDD_DIALOG_INPUT_SUBTYPE        175
#define IDR_MENU_ADD_SUB                176
#define IDB_LIST_TREASURE               178
#define IDD_FIND_TEMPLATE               179
#define IDD_DIALOG_PROGRESS             180
#define IDD_DIALOG_TEMPL_LIST           181
#define IDD_DIALOG_POLICY_TREE          182
#define IDD_EXPIRE_TIME                 183
#define IDD_TIME_LENGTH                 184
#define IDD_SET_TIME                    185
#define COLOR_LUMSCROLL                 702
#define COLOR_HUE                       703
#define COLOR_SAT                       704
#define COLOR_LUM                       705
#define COLOR_RED                       706
#define COLOR_GREEN                     707
#define COLOR_BLUE                      708
#define COLOR_CURRENT                   709
#define COLOR_RAINBOW                   710
#define COLOR_ALPHA                     711
#define COLOR_ADD                       712
#define COLOR_SOLID                     713
#define COLOR_MIX                       719
#define COLOR_BOX1                      720
#define COLOR_CUSTOM1                   721
#define COLOR_HUEACCEL                  723
#define COLOR_SATACCEL                  724
#define COLOR_LUMACCEL                  725
#define COLOR_REDACCEL                  726
#define COLOR_GREENACCEL                727
#define COLOR_BLUEACCEL                 728
#define COLOR_SOLID_LEFT                730
#define COLOR_SOLID_RIGHT               731
#define IDC_DIRLIST                     1000
#define IDC_EDIT_ITEM_INFOR             1000
#define IDC_COMBO_HIST                  1001
#define IDC_COMBOBOXEX_LOOKIN           1002
#define IDC_TREE_SORT_LIST              1002
#define IDC_BACKWARD                    1003
#define IDC_TREE_PROPERTY               1003
#define IDC_UP                          1004
#define IDC_STATIC_APPEND_PROPERTY      1004
#define IDC_FILELIST                    1005
#define IDC_COMBO_FILETYPE              1007
#define IDD_PATH_DIALOG                 1007
#define IDC_EDIT_TEMPLATE_NAME          1007
#define IDC_CHECK                       1008
#define IDC_STATIC_PREV                 1009
#define IDC_COMBO_TEMPLATE_LIST         1009
#define IDD_TASK_ID_SEL                 1009
#define IDC_STATIC_FILEINFO             1010
#define IDC_EDIT_NAME                   1010
#define IDD_PROC_TYPE_MASK              1010
#define IDC_STATIC_IMAGEINFO            1011
#define IDC_EDIT1                       1011
#define IDC_COMBO_EXT_ITEM2             1011
#define IDC_EDIT_WINDOW_ID              1011
#define IDD_MONSTER_FACTIONS            1011
#define IDC_EDIT2                       1012
#define IDC_COMBO_EXT_ITEM3             1012
#define IDC_EDIT3                       1013
#define IDC_COMBO_EXT_ITEM4             1013
#define IDC_COMBO_EXT_NUM               1014
#define IDC_EDIT_HOURS                  1014
#define IDC_EDIT_NAME1                  1015
#define IDC_EDIT_MINU                   1015
#define IDC_EDIT_NAME2                  1016
#define IDC_TREE_TEMPL                  1016
#define IDC_EDIT_SEC                    1016
#define IDC_EDIT_NAME3                  1017
#define IDC_EDIT_NAME4                  1018
#define IDC_COMBO_EXT_ITEM5             1019
#define IDC_CHECK1                      1020
#define IDC_TREE1                       1021
#define IDC_CHECK2                      1021
#define IDC_FILENAME                    1022
#define IDC_CHECK3                      1022
#define IDC_CHECK4                      1023
#define IDC_CHECK5                      1024
#define IDC_CHECK6                      1025
#define IDC_CHECK7                      1026
#define IDC_CHECK8                      1027
#define IDC_CHECK9                      1028
#define IDC_CHECK10                     1029
#define IDC_CHECK11                     1030
#define IDC_CHECK12                     1031
#define IDC_EDIT_VECOTR_X               1032
#define IDC_CHECK13                     1032
#define IDC_EDIT_VECOTR_Y               1033
#define IDC_CHECK14                     1033
#define IDC_EDIT_VECOTR_Z               1034
#define IDC_CHECK15                     1034
#define IDC_CHECK16                     1035
#define IDC_CHECK17                     1036
#define IDC_CHECK18                     1037
#define IDC_CHECK19                     1038
#define IDC_CHECK20                     1039
#define IDC_CHECK21                     1040
#define IDC_CHECK22                     1041
#define IDC_CHECK23                     1042
#define IDC_CHECK24                     1043
#define IDC_CHECK25                     1044
#define IDC_CHECK26                     1045
#define IDC_CHECK27                     1046
#define IDC_CHECK28                     1047
#define IDC_CHECK29                     1048
#define IDC_CHECK30                     1049
#define IDC_CHECK31                     1050
#define IDC_CHECK32                     1051
#define IDC_CHECK_AUTO_UPDATE           1052
#define IDC_SEL_COPY                    1053
#define IDC_CHECK_CUT_LINK_VSS          1053
#define IDC_SRC_TEMPL                   1054
#define IDC_TREE_TASK                   1055
#define IDC_TREE_TALK                   1056
#define IDC_RADIO_TALK_TYPE1            1057
#define IDC_RADIO_TALK_TYPE2            1058
#define IDC_COMBO_SERVICE               1059
#define IDC_EDIT_WINDOW_DESC            1060
#define IDC_EDIT_TALK_NAME              1061
#define IDC_RADIO_TALK_TYPE3            1061
#define IDC_EDIT_TALK_ID                1062
#define IDC_BUTTON_TALK_TEST            1063
#define IDC_STATIC_WINDOW               1064
#define IDC_STATIC_ID                   1065
#define IDC_STATIC_DESC                 1066
#define IDC_STATIC_SERVICE              1067
#define IDC_STATIC_SERVICE_TYPE         1068
#define IDC_BUTTON_DELETE_ITEM          1069
#define IDC_STATIC_COMMAND              1069
#define IDC_BUTTON_MOVE_ITEM_UP         1070
#define IDC_EDIT_COMMAND_NAME           1070
#define IDC_BUTTON_MOVE_ITEM_DOWN       1071
#define IDC_STATIC_SERVICE_TYPE2        1071
#define IDC_LIST_COMMAND                1072
#define IDC_STATIC_SERVICE_PARAMS       1072
#define IDC_EDIT_WNDTXT                 1073
#define IDC_BUTTON_SERVICE_LINK         1075
#define IDC_EDIT_SERVICE_LINK           1076
#define IDC_BUTTON1                     1077
#define IDC_SEARCH                      1077
#define IDC_BUTTON_DEL_TRIGGER          1077
#define IDC_BUTTON_SUB1                 1077
#define IDC_TEXT_INPUT                  1078
#define IDC_BUTTON_ADD_TRIGGER          1078
#define IDC_BUTTON_SUB2                 1078
#define IDC_WIPEOFF_LIST                1079
#define IDC_BUTTON_MOVE_UP              1079
#define IDC_PASSWD                      1080
#define IDC_BUTTON_MOVE_DOWN            1080
#define IDC_TARGET                      1081
#define IDC_BUTTON_POLICY_SAVE          1081
#define IDC_EDITMEMO                    1082
#define IDC_COMBO_SERVICE_PARAMS        1082
#define IDC_BUTTON_STOP_TRIGGER         1082
#define IDC_TEXT                        1083
#define IDC_BUTTON_RUN_TRIGGER          1083
#define IDC_TREE_POLICY                 1084
#define IDC_BUTTON_COPY_TRIGGER         1085
#define IDC_COMBO_OPERATION_TYPE        1086
#define IDC_BUTTON_PASTE_TRIGGER        1086
#define IDC_LIST_OPERATION              1088
#define ID_MODIFY                       1089
#define IDC_LISTBOX_OPERATION           1090
#define IDC_EDIT_PROGRAM                1091
#define IDC_COMBO_FUNC                  1093
#define IDC_EDIT_PARAM_FLOAT            1094
#define IDC_COMBO_TARGET_TYPE           1095
#define IDC_EDIT_PARAM_INT              1095
#define IDC_CHECK_WUXIA                 1097
#define IDC_CHECK_FASHI                 1098
#define IDC_CHECK_YAOSHOU               1099
#define IDC_CHECK_YULIN                 1100
#define IDC_CHECK_YUMANG                1101
#define IDC_CHECK_WUSHI                 1102
#define IDC_CHECK_YAOJING               1103
#define IDC_LIST_TRIGGER                1104
#define IDC_CHECK_CIKE                  1104
#define IDC_EDIT_TRIGGER_NAME           1105
#define IDC_CHECK_JIANLING              1105
#define IDC_STATIC_POLICYNAME           1106
#define IDC_EDIT_TRIGGER_ID             1106
#define IDC_CHECK_MEILING               1106
#define IDC_CHECK_YEYING                1107
#define IDC_EDIT_RUN_LOG                1108
#define IDC_CHECK_YUEXIAN               1108
#define IDC_STATIC_HP                   1109
#define IDC_EDIT_HP                     1110
#define IDC_CHECK_ACTIVE                1114
#define IDC_EDIT_SUB1                   1115
#define IDC_EDIT_SUB2                   1116
#define IDC_BUTTON_EVENT_RANDOM         1117
#define IDC_BUTTON_EVENT_KILLPLAYER     1118
#define IDC_RADIO_ATTACK_EFFECT         1118
#define IDC_BUTTON_EVENT_ATTACKSTART    1119
#define IDC_RADIO_ATTACT_NOEFFECT       1119
#define IDC_LIST_ITEM                   1119
#define IDC_BUTTON_EVENT_DIED           1120
#define IDC_BUTTON_EVENT_TIME_POINT     1121
#define IDC_LIST_MOUNSTER               1122
#define IDC_BUTTON_EVENT_REACHEND       1122
#define IDC_BUTTON_EVENT_STOPFIGHT      1123
#define IDC_COMBO_TYPE                  1124
#define IDC_BUTTON_EVENT_AT_HISTORY_STAGE 1124
#define IDC_RADIO_CHECK_OUT             1125
#define IDC_BUTTON_EVENT_END_HISTORY_STAGE 1125
#define IDC_BUTTON_EVENT_REACHEND2      1125
#define IDC_RADIO_CHECK_IN              1126
#define IDC_LIST_TEMPLATE_EXT           1126
#define IDC_BUTTON_EVENT_HASFILTER      1126
#define IDC_LIST_ALL_TREASURE           1127
#define IDC_FLOAT_ICON                  1128
#define IDC_LIST_TREASURE               1129
#define IDC_EDIT_YEAR                   1130
#define IDC_EDIT_MONTH                  1131
#define IDC_EDIT_DAY                    1132
#define IDC_EDIT_SUB_NAME               1134
#define IDC_TREE_TREASURE               1135
#define IDC_PROC_CHECK1                 1136
#define IDC_PROC_CHECK2                 1137
#define IDC_PROC_CHECK3                 1138
#define IDC_PROC_CHECK4                 1139
#define IDC_PROC_CHECK5                 1140
#define IDC_PROC_CHECK6                 1141
#define IDC_PROC_CHECK7                 1142
#define IDC_PROC_CHECK8                 1143
#define IDC_PROC_CHECK9                 1144
#define IDC_PROC_CHECK10                1145
#define IDC_COMBO1                      1145
#define IDC_PROC_CHECK11                1146
#define IDC_PROGRESS1                   1146
#define IDC_PROC_CHECK12                1147
#define IDC_STATIC1                     1147
#define IDC_PROC_CHECK13                1148
#define IDC_LIST1                       1148
#define IDC_PROC_CHECK14                1149
#define IDBUTTON1                       1149
#define IDC_BUTTON_EXPORT_TXT_TEST      1150
#define IDC_PROC_CHECK15                1150
#define IDBUTTON2                       1150
#define IDC_EDIT_POLICY_COPY_PATH       1151
#define IDC_BUTTON_POLICY_COPY_PATH     1152
#define IDC_EDIT_HOUR                   1153
#define IDC_EDIT_MINUTE                 1154
#define IDC_EDIT_SECOND                 1155
#define IDC_TAB_TIME                    1156
#define ID_CREATE_OBJECT                32771
#define ID_CREATE_OBJECT_EXT            32772
#define ID_OPTION_VSS                   32773
#define ID_VSS_CHECK_IN                 32774
#define ID_VSS_CHECK_OUT                32775
#define ID_VSS_FRESH                    32777
#define ID_EDIT_TEMPLATE_PROPERTY       32778
#define ID_SAVE_ALL_DOC                 32779
#define ID_EXPORT_DATA                  32780
#define ID_MODIFIED_OBJECT_EXT          32781
#define ID_TEST_TALK                    32782
#define ID_CREATE_TALK_WINDOW           32783
#define ID_MODIFY_TALK_WINDOW           32784
#define ID_CHECK                        32785
#define ID_POLICY_EDITOR                32786
#define ID_CREATE_POLICY                32787
#define ID_POLICY_CHECK_OUT             32791
#define ID_POLICY_CHECK_IN              32792
#define ID_EXPORT_POLICY_DATA           32793
#define ID_TRANS_VERSION                32795
#define ID_GET_POLICY_DATA              32796
#define ID_MOUNSTER_FALL_ITEM_EDITOR    32797
#define ID_VSS_CHECK_IN_ALL             32798
#define ID_VSS_CHECK_OUT_ALL            32799
#define ID_VSS_UNDO_CHECK_OUT           32800
#define ID_ITEMS_EDITOR                 32801
#define ID_MENU_ADDSUB                  32802
#define ID_MENU_DELSUB                  32803
#define ID_MENU_ADD_TREASURE            32804
#define ID_MENU_DEL_TREASURE            32805
#define ID_AUTO_RESAVE_TEMPLATE         32806
#define ID_ITEMS2_EDITOR                32807
#define ID_QUICKLY_GET_ALL_DATA         32808
#define IDT_FIND_TEMPLATE               32809
#define ID_FIND_TEMPLATE                32810
#define ID_BTN_FIND_POLICY              32811
#define ID_EDIT_FIND_POLICY             32812
#define ID_TEST_EXPORT_DATA             32813
#define ID_POLICY_UNDO_CHECK_OUT        32814

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        186
#define _APS_NEXT_COMMAND_VALUE         32815
#define _APS_NEXT_CONTROL_VALUE         1154
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
