//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ElementEditor.rc
//
#define ID_DEL_POS                      3
#define ID_MUSIC_DEL                    3
#define ID_GATHER_ADD                   3
#define IDC_SERTCH                      3
#define ID_CHECK_IN                     3
#define ID_SET_NULL                     3
#define IDSELECTALL                     3
#define ID_DEL_POS2                     4
#define ID_GATHER_MODIFY                4
#define ID_ADD_NEWOBJECT                4
#define ID_GATHER_DEL                   5
#define ID_DEL_OBJECT                   5
#define ID_EXPORT                       6
#define ID_EXPORT_TXT                   6
#define IDD_ABOUTBOX                    100
#define IDD_COMMONFILE_DIALOG           102
#define IDR_MAINFRAME                   128
#define IDR_ELEMENTYPE                  129
#define IDD_DIALOG1                     130
#define IDR_VIEWFRAME                   131
#define IDD_NEWMAP                      132
#define IDD_HEIGHTMAP                   133
#define IDR_HEIGHTMAP                   134
#define IDD_NEWHEIGHTMAP                135
#define IDC_CHOOSECOLOR_DIALOG          136
#define IDD_OPTIONS                     138
#define IDD_RENDEROPT                   139
#define IDD_SURFACES                    140
#define IDI_NEWLAYER                    141
#define IDD_SELECTFILE                  141
#define IDI_DELETE                      142
#define IDI_MOVEUP                      143
#define IDI_MOVEDOWN                    144
#define IDD_SAVEAS                      145
#define IDD_EXPGAMEDATA                 146
#define IDI_OPEN                        147
#define IDD_CUSTOM_VECTOR_DLG           147
#define IDI_SAVE                        148
#define IDD_LIGHTING                    149
#define IDR_LIGHTING                    150
#define IDD_TERRAIN_MODIFY              151
#define IDR_BRUSH                       152
#define IDD_BRUSH_SET                   158
#define IDD_TERRAIN_MODIFY_STRETCH      163
#define IDD_TERRAIN_MODIFY_NOISE        164
#define IDD_TERRAIN_MODIFY_LAYMASK      165
#define IDD_TERRAIN_MODIFY_SMOOTH       166
#define IDD_SCENE_OBJECT                167
#define IDD_TERRAIN_MODIFY_LAYMASKSMOOTH 168
#define IDD_PROPERTY_DIALOG             169
#define IDD_SCENE_OBJECT_LIGHT          170
#define IDD_SCENE_OBJECT_PROPERTY       171
#define IDD_SCENE_OBJECT_MODEL_LIST     172
#define IDD_SCENE_OBJECTS_LIST          173
#define IDC_CURSOR_OBJECT_MOVE          174
#define IDC_CURSOR_CROSS                176
#define IDC_CURSOR_SCALE                177
#define IDC_CURSOR_ROTATE               178
#define IDD_SCENE_OBJECT_SKY            179
#define IDR_SURFACES                    182
#define IDD_TERRAIN_MODIFY_PLANTS       183
#define IDI_PLANT_ADD_SORT              184
#define IDI_DELETE_FROM_TERRAIN         185
#define IDD_PLANTS_IN_SORT_NAME         186
#define IDC_CURSOR_OBJECTADD            188
#define IDD_DIALOG_VERNIER_SET          189
#define IDD_TREE_TYPE_ADD               190
#define IDI_ICON1                       191
#define IDI_ICON2                       192
#define IDI_ICON3                       193
#define IDI_ICON4                       194
#define IDD_AUTOPARTHM                  195
#define IDI_ICON5                       196
#define IDI_ICON6                       197
#define IDI_ICON7                       198
#define IDI_ICON8                       199
#define IDD_AI_AREA                     200
#define IDD_AI_PROPERTY                 201
#define IDD_FIXED_NPC_SEL               202
#define IDD_EXP_GAME_DATA               203
#define IDD_MODIFIED_TERRAIN_PROFILE    204
#define IDD_TERRAIN_CONNECT             205
#define IDB_QUAD_1                      206
#define IDB_QUAD_2                      207
#define IDB_QUAD_3                      208
#define IDB_QUAD_4                      209
#define IDD_BEZIER_MERGE                211
#define IDD_MONSTER_FINDER              213
#define IDD_TERRAIN_BLOCK_VIEW_DLG      214
#define IDD_LOG_DLG                     215
#define IDD_BEZIER_ID_SEL               216
#define IDD_DIALOG_NATRUE               217
#define IDD_DIALOG_RES_MAN              218
#define IDD_DIALOG_VSS_OPTION           219
#define IDB_BITMAP_FLAGS                221
#define IDD_DIALOG_EXP_RES              222
#define IDD_PRICIENT_NPC_SEL            223
#define IDD_PRECINCT_NPC_IMPORT         224
#define IDD_MOVE_ALL_OBJ_HEIGHT         225
#define IDD_DIALOG_MUSIC_SEL            227
#define IDD_GATER_AREA                  228
#define IDD_GATHER_PROPERTY_DLG         229
#define IDD_DIALOG_RES_FINDER           230
#define IDD_CLOUD_SET_DLG               231
#define IDD_DIALOG_DEL_LIST             232
#define IDD_DIALOG_DAY_NIGHT            233
#define IDD_DIALOG_SET_WORKSPACE        234
#define IDD_DIALOG_CREATE_WORKSPACE     235
#define IDD_DIALOG_EXP_PATH_SEL         236
#define IDD_VSS_LOG                     237
#define IDD_DIALOG_HULL_PROPERTY        238
#define IDD_DIALOG_STAT                 239
#define IDD_DIALOG_MODEL_CHANGED        240
#define IDD_DIALOG_EXP_LIT              241
#define IDD_DIALOG_DYNAMIC_OBJECT       242
#define IDD_DIALOG_DYNAMIC_OBJECT_MAN   243
#define IDD_DIALOG_DYNAMIC_OBJECT_SEL   244
#define IDI_WRITEABLE                   245
#define IDI_READONLY                    246
#define IDD_DIALOG_CONTROLLER_OBJECT_SEL 247
#define IDD_DIALOG_CONTROLLER_OBJECT_MAN 248
#define IDD_DIALOG_CONTROLLER_OBJECT    249
#define IDD_DIALOG_STAT_FILTER          250
#define IDD_TERRAIN_BRUSH_SEL           251
#define IDD_DIALOG_EXP_COPY             252
#define IDR_MENU_TREE_SET               253
#define IDD_MERGE_PLAYERPASSMAP         254
#define IDD_RANDOM_MAP_INFO             255
#define COLOR_LUMSCROLL                 702
#define COLOR_HUE                       703
#define COLOR_SAT                       704
#define COLOR_LUM                       705
#define COLOR_RED                       706
#define COLOR_GREEN                     707
#define COLOR_BLUE                      708
#define COLOR_CURRENT                   709
#define COLOR_RAINBOW                   710
#define COLOR_ALPHA                     711
#define COLOR_ADD                       712
#define COLOR_SOLID                     713
#define COLOR_MIX                       719
#define COLOR_BOX1                      720
#define COLOR_CUSTOM1                   721
#define COLOR_HUEACCEL                  723
#define COLOR_SATACCEL                  724
#define COLOR_LUMACCEL                  725
#define COLOR_REDACCEL                  726
#define COLOR_GREENACCEL                727
#define COLOR_BLUEACCEL                 728
#define COLOR_SOLID_LEFT                730
#define COLOR_SOLID_RIGHT               731
#define IDC_TREE_DIRECTORY              1000
#define IDC_DIRLIST                     1000
#define IDC_EDIT_BORDERLEN              1001
#define IDC_LIST_FILE                   1001
#define IDC_EDIT_TILESIZE               1001
#define IDC_COMBO_HIST                  1001
#define IDC_STATIC_TITLE                1002
#define IDC_STATIC_PROMPT               1002
#define IDC_COMBOBOXEX_LOOKIN           1002
#define IDC_STATIC_HEIGHTMAPVIEW        1003
#define IDC_BACKWARD                    1003
#define IDC_UP                          1004
#define IDC_STATIC_HEIGHTMAPVIEW2       1004
#define IDC_FILELIST                    1005
#define IDC_STATIC_HEIGHTMAPVIEW3       1005
#define IDC_EDIT_FILENAME               1007
#define IDD_PATH_DIALOG                 1007
#define IDC_COMBO_FILETYPE              1007
#define IDC_BTN_BROWSE                  1008
#define IDC_CHECK                       1008
#define IDD_MEMOEDIT_DIALOG             1008
#define IDC_STATIC_SCALE                1009
#define IDC_STATIC_PREV                 1009
#define IDC_COMBO_SIZE                  1010
#define IDC_STATIC_FILEINFO             1010
#define IDC_EDIT_CAMERAMOVE             1011
#define IDC_STATIC_IMAGEINFO            1011
#define IDD_MONSTER_FACTIONS            1011
#define IDC_EDIT_CAMERAROT              1012
#define IDD_EXPORT_BHT                  1012
#define IDC_CHECK_ALONGGROUND           1013
#define IDD_EXPORT_PATH_INFO            1013
#define IDC_CHECK_OBJECT_ADD_CONTINUE   1014
#define IDD_SCENE_OBJECT_FINDER         1014
#define IDC_SPIN_CAMERAROT              1015
#define IDC_SPIN_CAMERAMOVE             1016
#define IDC_CHECK_PICK_STATICOBJECT     1017
#define IDC_CHECK_PICK_LIGHT            1018
#define IDC_LIST_LAYERS                 1019
#define IDC_CHECK_PICK_AUDIO            1019
#define IDC_CHECK_PICK_BOXAREA          1020
#define IDC_CHECK_ENABLE                1021
#define IDC_TREE1                       1021
#define IDC_CHECK_PICK_DUMMY            1021
#define IDC_COMBO_PROJAXIS              1022
#define IDC_FILENAME                    1022
#define IDC_CHECK_PICK_SPECIALLY        1022
#define IDC_EDIT_USCALE                 1023
#define IDC_CHECK_PICK_WATER            1023
#define IDC_CHECK4                      1023
#define IDC_EDIT_VSCALE                 1024
#define IDC_CHECK_PICK_AIAREA           1024
#define IDC_CHECK5                      1024
#define IDC_SPIN_USCALE                 1025
#define IDC_CHECK_PICK_PATH             1025
#define IDC_CHECK6                      1025
#define IDC_CHECK_PICK_NPC_PATH         1025
#define IDC_SPIN_VSCALE                 1026
#define IDC_CHECK_PICK_CRITTER          1026
#define IDC_CHECK7                      1026
#define IDC_CHECK_AUTOGENMASK           1027
#define IDC_CHECK_PICK_SKIN_MODEL       1027
#define IDC_CHECK8                      1027
#define IDC_CHECK_SMOOTH                1028
#define IDC_CHECK9                      1028
#define IDC_CHECK_SHOW_HULL             1028
#define IDC_EDIT_ALTISTART              1029
#define IDC_CHECK10                     1029
#define IDC_CHECK_PICK_PRECINCT         1029
#define IDC_SPIN_ALTISTART              1030
#define IDC_CHECK11                     1030
#define IDC_CHECK_PICK_GATHER           1030
#define IDC_EDIT_ALTIEND                1031
#define IDC_RECT_PROPERIES              1031
#define IDC_CHECK12                     1031
#define IDC_CHECK_BEZIER_PT_SNAP        1031
#define IDC_SPIN_ALTIEND                1032
#define IDC_EDIT_VECOTR_X               1032
#define IDC_CHECK13                     1032
#define IDC_CHECK_PICK_RANGE            1032
#define IDC_EDIT_SLOPESTART             1033
#define IDC_EDIT_VECOTR_Y               1033
#define IDC_CHECK14                     1033
#define IDC_CHECK_PICK_CLOUD_BOX        1033
#define IDC_SPIN_SLOPESTART             1034
#define IDC_EDIT_VECOTR_Z               1034
#define IDC_CHECK15                     1034
#define IDC_CHECK_PICK_INSTANCE_BOX     1034
#define IDC_EDIT_SLOPEEND               1035
#define IDC_CHECK16                     1035
#define IDC_CHECK_PICK_DYNAMIC          1035
#define IDC_SPIN_SLOPEEND               1036
#define IDC_CHECK17                     1036
#define IDC_CHECK_SHOW_HULL2            1036
#define IDC_BTN_IMPORTMASK              1037
#define IDC_CHECK18                     1037
#define IDC_BTN_EXPORTMASK              1038
#define IDC_CHECK19                     1038
#define IDC_CHECK_PICK_NON_NPC_PATH     1038
#define IDC_BTN_ADDLAYER                1039
#define IDC_CHECK20                     1039
#define IDC_BTN_DELLAYER                1040
#define IDC_CHECK21                     1040
#define IDC_BTN_MOVEUPLAYER             1041
#define IDC_CHECK22                     1041
#define IDC_BTN_MOVEDNLAYER             1042
#define IDC_CHECK23                     1042
#define IDC_STATIC_TEXTURE              1043
#define IDC_CHECK24                     1043
#define IDC_BTN_LOADTEXTURE             1044
#define IDC_CHECK25                     1044
#define IDC_STATIC_AUTOMASK             1045
#define IDC_CHECK26                     1045
#define IDC_STATIC_TERRAINVIEW          1046
#define IDC_CHECK27                     1046
#define IDC_CHECK_TERRAINTEXTURE        1047
#define IDC_CHECK_IMMEMASKPAINT         1047
#define IDC_BTN_LOADTEXTURE2            1047
#define IDC_BTN_LOADSPECUMAP            1047
#define IDC_CHECK28                     1047
#define IDC_STATIC_SPECUMAP             1048
#define IDC_CHECK_RENDER_SKY            1048
#define IDC_CHECK29                     1048
#define IDC_BTN_DELLAYER2               1049
#define IDC_BTN_DELSPECUMAP             1049
#define IDC_CHECK_RENDER_SHOW_NAME      1049
#define IDC_CHECK30                     1049
#define IDC_EDIT_PROJNAME               1050
#define DC_CHECK_RENDER_ENABLE_FOG      1050
#define IDC_CHECK31                     1050
#define IDC_RADIO1                      1051
#define IDC_CHECK32                     1051
#define DC_CHECK_RENDER_SAMPLE_WATER    1051
#define IDC_RADIO2                      1052
#define IDC_RADIO_ZY                    1053
#define IDC_RADIO_3                     1053
#define IDC_RADIO_LINK3                 1053
#define IDC_LIST_PROJECT                1054
#define IDC_RADIO_4                     1054
#define IDC_RADIO_LINK4                 1054
#define IDC_EDIT_COLUMN                 1056
#define IDC_COMBO_MASKTILE              1057
#define IDC_BTN_LOADPROJLIST            1058
#define IDC_BTN_SAVEPROJLIST            1059
#define IDC_BTN_MOVEUPPROJ              1060
#define IDC_BTN_MOVEDNPROJ              1061
#define IDC_PROGRESS                    1063
#define IDC_EDIT_LOG                    1064
#define IDC_STATIC_MAPPIECE             1065
#define IDC_RADIO3                      1066
#define IDC_EDIT_MINHEIGHT              1067
#define IDC_EDIT_MAXHEIGHT              1068
#define IDC_STATIC_MASKTITLE            1068
#define IDC_COMBO_AUTOMASKSIZE          1069
#define IDC_SLIDER_SUNDIR               1070
#define IDC_SLIDER_SUNHEIGHT            1071
#define IDC_BTN_AMBIENT                 1072
#define IDC_BTN_SUNCOLOR                1073
#define IDC_BTN_GENLIGHTMAP             1074
#define IDC_EDIT1                       1076
#define IDC_EDIT_VIEWRADIUS             1076
#define IDC_EDIT_SKY_TEX1               1076
#define IDC_EDIT_PLANTS_NAME            1076
#define IDC_EDIT_TEXTURE_PATH1          1076
#define IDC_EDIT_SUNDIRPOS              1076
#define IDC_EDIT_USER_BRUSH_NAME        1076
#define IDC_EDIT_POSX                   1076
#define IDC_EDIT_SPEED_TREE_NAME        1076
#define IDC_EDIT_NPC_NUM                1076
#define IDC_EDIT_PATH_MAP1              1076
#define IDC_EDIT_BEZIERA                1076
#define IDC_MONSTER_KEY                 1076
#define IDC_EDIT_SPEED                  1076
#define IDC_EDIT_USER_NAME              1076
#define IDC_EDIT_PATH                   1076
#define IDC_EDIT_NAME                   1076
#define IDC_EDIT_DELTA                  1076
#define IDC_EDIT_NUM                    1076
#define IDC_EDIT_KEYWORD                1076
#define IDC_EDIT_SPRITE_NUM             1076
#define IDC_EDIT_WORKSPACE_NAME         1076
#define IDC_EDIT_VSS_LOG                1076
#define IDC_EDIT_MOUNSTER_ID            1076
#define IDC_EDIT_EXPORT_PATH            1076
#define IDC_EDIT_ID                     1076
#define IDC_EDIT_BURSH_NAME             1076
#define IDC_EDIT_COPYS                  1076
#define IDC_EDIT_SEARCH                 1076
#define IDC_CHECK1                      1077
#define IDC_TERRAIN_MODIFY_STRETCH      1077
#define IDC_CHECK_LIGHTING              1077
#define IDC_CHECK_MASKAXIS_X            1077
#define IDC_EDIT_SKY_TEX2               1077
#define IDC_CHECK_PLANTS_SHOW           1077
#define IDC_EDIT_SUNHEIPOS              1077
#define IDC_CHECK_USER_BRUSH            1077
#define IDC_EDIT_POSY                   1077
#define IDC_EDIT_DDS_NAME               1077
#define IDC_EDIT_NPC_FRESH              1077
#define IDC_EDIT_PATH_MAP2              1077
#define IDC_EDIT_SIZE                   1077
#define IDC_EDIT_PASSWORD               1077
#define IDC_CHECK_LOCK_MAP_EDGE         1077
#define IDC_EDIT_X                      1077
#define IDC_EDIT_FRESH                  1077
#define IDC_CHECK_EXA                   1077
#define IDC_CHECK_TEXTURE               1077
#define IDC_EDIT_SPRITE_SIZE            1077
#define IDC_RADIO_SKIP_CO               1077
#define IDC_EDIT_AREA_NUM               1077
#define IDC_EDIT_OBJ_NAME               1077
#define IDC_CHECK_COPY0                 1077
#define IDC_CHK_CONNECT1                1077
#define IDC_CHK_RANDOM_MAP              1077
#define IDC_CHECK2                      1078
#define IDC_TERRAIN_MODIFY_EMPTY        1078
#define IDC_TERRAIN_MODIFY_STRETCH2     1078
#define IDC_CHECK_MASKAXIS_Y            1078
#define IDC_CHECK_ENABLENOISE           1078
#define IDC_SCENE_OBJECT_LIGHT          1078
#define IDC_EDIT_SKY_TEX3               1078
#define IDC_EDIT_POSZ                   1078
#define IDC_CHECK_GRASS_ENABLEALPHA     1078
#define IDC_EDIT_TREE_NAME              1078
#define IDC_EDIT_SUNPOWER               1078
#define IDC_EDIT_NPC_OFFSET_T           1078
#define IDC_EDIT_PATH_MAP4              1078
#define IDC_CHECK_LIGHTING_TRANS        1078
#define IDC_EDIT_SERVER_PATH            1078
#define IDC_EDIT_Y                      1078
#define IDC_EDIT_OFFSET_Y               1078
#define IDC_EDIT_SPRITE_DIST            1078
#define IDC_RADIO_SKIP_TA               1078
#define IDC_EDIT_FIXED_NUM              1078
#define IDC_EDIT_DYNAMIC_OBJECT_PATH    1078
#define IDC_EDIT_ACTIVE_TIMES           1078
#define IDC_CHECK_COPY1                 1078
#define IDC_CHK_CONNECT2                1078
#define IDC_SLIDER_BRUSHRADIUS          1079
#define IDC_TERRAIN_MODIFY_SMOOTH       1079
#define IDC_TERRAIN_MODIFY_STRETCH3     1079
#define IDC_CHECK_MASKAXIS_Z            1079
#define IDC_EDIT_SKY_TEX4               1079
#define IDC_SCENE_OBJECT_AUDIO          1079
#define IDC_EDIT_VERNIER_WIDTH          1079
#define IDC_EDIT_NPC_OFFSET_W           1079
#define IDC_EDIT_PATH_MAP3              1079
#define IDC_EDIT_BEZIERB                1079
#define IDC_EDIT_Z                      1079
#define IDC_EDIT_SUNPOWER2              1079
#define IDC_EDIT_TOTAL                  1079
#define IDC_CHECK_EXPORT_MINI_MAP       1079
#define IDC_EDIT_STOP_TIMES             1079
#define IDC_CHECK_COPY2                 1079
#define IDC_TERRAIN_MODIFY_NOISE        1080
#define IDC_SLIDER_BRUSHRADIUS2         1080
#define IDC_SLIDER_BRUSHHARD            1080
#define IDC_TERRAIN_MODIFY_STRETCH4     1080
#define IDC_SCENE_OBJECT_MODEL          1080
#define IDC_EDIT_SKY_TEX5               1080
#define IDC_EDIT_TEXTURE_PATH2          1080
#define IDC_EDIT_NPC_DIE_NUM            1080
#define IDC_EDIT_PATH_MAP5              1080
#define IDC_EDIT_CONTROLLERID           1080
#define IDC_CHECK_COPY3                 1080
#define IDC_TERRAIN_MODIFY_LAYMASK      1081
#define IDC_TERRAIN_MODIFY_STRETCH5     1081
#define IDC_EDIT_SKY_TEX6               1081
#define IDC_SCENE_OBJECT_AREA           1081
#define IDC_EDIT_NPC_ID                 1081
#define IDC_CHECK_COPY4                 1081
#define IDC_TERRAIN_MODIFY_LAYMASK_SOFT 1082
#define IDC_TERRAIN_MODIFY_STRETCH6     1082
#define IDC_EDITMEMO                    1082
#define IDC_SCENE_OBJECT_AI             1082
#define IDC_EDIT_PATH_ID                1082
#define IDC_CHECK_COPY5                 1082
#define IDC_EDIT_BRUSHRADIUS            1083
#define IDC_SCENE_OBJECT_SKYBOX         1083
#define IDC_TERRAIN_MODIFY_PLANT        1083
#define IDC_EDIT_NPC_DIE_DISAPEAR_TIME  1083
#define IDC_CHECK_COPY6                 1083
#define IDC_SPIN_BRUSHRADIUS            1084
#define IDC_SCENE_OBJECT_WATER          1084
#define IDC_CHECK_COPY7                 1084
#define IDC_EDIT_NPC_FRESHMIN           1084
#define IDC_RADIO_BRUSHCIRCLE           1085
#define IDC_EDIT_BRUSHRADIUS2           1085
#define IDC_EDIT_BRUSHHARD              1085
#define IDC_SCENE_OBJECT_VERNIER        1085
#define IDC_TERRAIN_OBSTRUCT_RED        1085
#define IDC_CHECK_COPY8                 1085
#define IDC_RADIO_BRUSHRECT             1086
#define IDC_SPIN_BRUSHRADIUS2           1086
#define IDC_SPIN_BRUSHHARD              1086
#define IDC_SCENE_OBJECT_DUMMY          1086
#define IDC_TERRAIN_OBSTRUCT_GREEN      1086
#define IDC_CHECK_COPY9                 1086
#define IDC_RADIO_BRUSHFLAT             1087
#define IDC_SCENE_OBJECT_SKINMODEL      1087
#define IDC_TERRAIN_OBSTRUCT_START      1087
#define IDC_CHECK_COPY10                1087
#define IDC_TERRAIN_OBSTRUCT2_RED       1087
#define IDC_TERRAIN_FILTER_DLG          1088
#define IDC_SCENE_OBJECT_CRITTER        1088
#define IDC_TERRAIN_OBSTRUCT_CONVEX     1088
#define IDC_CHECK_COPY11                1088
#define IDC_EDIT_BRUSHHEIGHT            1089
#define IDC_SCENE_OBJECT_PRECINCT       1089
#define IDC_TERRAIN_OBSTRUCT_MAP_YELLOW 1089
#define IDC_CHECK_COPY12                1089
#define IDC_SLIDER_BRUSHHEIGHT          1090
#define IDC_EDIT_BRUSHHEIGHT2           1090
#define IDC_EDIT_NOISERADIUS            1090
#define IDC_SCENE_OBJECT_FIXNPC         1090
#define IDC_CHECK_COPY13                1090
#define IDC_TERRAIN_OBSTRUCT2_GREEN     1090
#define IDC_SPIN_BRUSHHEIGHT            1091
#define IDC_EDIT_NOISEDELTA             1091
#define IDC_SCENE_OBJECT_GATHER         1091
#define IDC_CHECK_COPY14                1091
#define IDC_TERRAIN_OBSTRUCT2_YELLOW    1091
#define IDC_RADIO_BRUSHSMOOTH           1092
#define IDC_SPIN_BRUSHHEIGHT2           1092
#define IDC_SPIN_NOISERADIUS            1092
#define IDC_SCENE_OBJECT_RANGE          1092
#define IDC_CHECK_COPY15                1092
#define IDC_STATIC_HARD                 1093
#define IDC_SPIN_BRUSHHEIGHT3           1093
#define IDC_SPIN_NOISEWAVELEN           1093
#define IDC_SPIN_NOISEDELTA             1093
#define IDC_SCENE_OBJECT_CLOUD_SET      1093
#define IDC_CHECK_COPY16                1093
#define IDC_SLIDER_BRUSHHGRAY           1094
#define IDC_EDIT_STRETCH_NOISE_RADIUS   1094
#define IDC_SCENE_OBJECT_CLOUD_BOX      1094
#define IDC_CHECK_COPY17                1094
#define IDC_EDIT_BRUSHHGRAY             1095
#define IDC_EDIT_NOISEPERSISTENCE       1095
#define IDC_SPIN_STRETCH_NOISE_RADIUS   1095
#define IDC_SCENE_OBJECT_BOX_INSTANCE   1095
#define IDC_CHECK_COPY18                1095
#define IDC_SPIN_BRUSHHGRAY             1096
#define IDC_SPIN_NOISEPERSISTENCE       1096
#define IDC_EDIT_STRETCH_NOISE_PERSISTENCE 1096
#define IDC_SCENE_OBJECT_DYNAMIC_ADD    1096
#define IDC_CHECK_COPY19                1096
#define IDC_SLIDER_BRUSHLAYHARD         1097
#define IDC_SPIN_STRETCH_NOISE_PERSISTENCE 1097
#define IDC_CHECK_COPY20                1097
#define IDC_SPIN_BRUSHLAYHARD           1098
#define IDC_RADIO_HEIGHTADD             1098
#define IDC_CHECK_COPY21                1098
#define IDC_EDIT_BRUSHLAYHARD           1099
#define IDC_RADIO_HEIGHTSUB             1099
#define IDC_CHECK_COPY22                1099
#define IDC_TERRAIN_MODIFY_LAYLIST      1100
#define IDC_CHECK_COPY23                1100
#define IDC_FRESH_LAYER_LIST            1101
#define IDC_CHECK_COPY24                1101
#define IDC_EDIT_NOISEWAVELEN           1102
#define IDC_RADIO_MASKPAINT_CLRADD      1102
#define IDC_CHECK_COPY25                1102
#define IDC_RADIO_MASKPAINT_CLRSUB      1103
#define IDC_CHECK_COPY26                1103
#define IDC_COMBO1                      1104
#define IDC_COMBO_MAPSIZE               1104
#define IDC_COMBO_NOISE_TYPE            1104
#define IDC_COMBO_WEIGHT                1104
#define IDC_COMBO_NPC                   1104
#define IDC_COMBO_SEL                   1104
#define IDC_COMBO_LAY                   1104
#define IDC_COMBO_RES_TYPE              1104
#define IDC_COMBO_GATHER_TYPE           1104
#define IDC_COMBO_CLOUD_GROUP           1104
#define IDC_COMBO_COPY_SEL              1104
#define IDC_COMBO1_YEAR                 1104
#define IDC_CHECK_COPY27                1104
#define IDC_COMBO_SEL_PPASSMAP_LAYER    1104
#define IDC_COMBO_LAYER                 1104
#define IDC_SLIDER_BRUSHSMOOTH          1105
#define IDC_COMBO_RES_REF_TYPE          1105
#define IDC_COMBO_PATH_LOOP_TYPE        1105
#define IDC_COMBO_COPY                  1105
#define IDC_CHECK_COPY28                1105
#define IDC_EDIT_BRUSHSMOOTH            1106
#define IDC_COMBO_PATH_SPEED_TYPE       1106
#define IDC_COMBO1_MOUTH                1106
#define IDC_CHECK_COPY29                1106
#define IDC_SPIN_BRUSHSMOOTH            1107
#define IDC_COMBO1_WEEK                 1107
#define IDC_CHECK_COPY30                1107
#define IDC_COMBO_STRETCH_TYPE          1108
#define IDC_COMBO1_DAY                  1108
#define IDC_CHECK_COPY31                1108
#define IDC_STATIC_HEIGHT               1109
#define IDC_COMBO1_HOURS                1109
#define IDC_STATIC_SOFTBRUSH            1110
#define IDC_COMBO1_MINU                 1110
#define IDC_STATIC_PERSISTENCE          1111
#define IDC_COMBO2_YEAR                 1111
#define IDC_STATIC_RADIUS               1112
#define IDC_COMBO2_MOUTH                1112
#define IDC_STATIC_LIGHTINGVIEW         1113
#define IDC_COMBO2_WEEK                 1113
#define IDC_TERRAIN_MODIFY_LAYLISTSMOOTH 1114
#define IDC_COMBO2_DAY                  1114
#define IDC_SLIDER_LAYMASKSMOOTH        1115
#define IDC_COMBO2_HOURS                1115
#define IDC_EDIT_LAYMASKSMOOTH          1116
#define IDC_COMBO2_MINU                 1116
#define IDC_SPIN_LAYMASKSMOOTH          1117
#define IDC_STATIC_BRUSHHEIGHT          1118
#define IDC_STATIC_AMBIENT              1121
#define IDC_STATIC_SUNCOLOR             1122
#define IDC_STATIC_SUNDIRPOS            1123
#define IDC_STATIC_SUNHEIPOS            1124
#define IDC_EDIT_FOGSTART               1125
#define IDC_EDIT_FOGEND                 1126
#define IDC_EDIT_FOGDENSITY             1127
#define IDC_STATIC_FOGCOLOR             1128
#define IDC_SCENE_OBJECT_PROPERTY_LIST  1129
#define IDC_BUTTON_OBJECT_RESET         1130
#define IDC_BUTTON_OBJECT_UPDATE        1131
#define IDC_SCENE_MODEL_TREE            1131
#define IDC_SCENE_TREE                  1133
#define IDC_BUTTON_SKY1                 1134
#define IDC_BUTTON_SKY2                 1135
#define IDC_CREATE_SKYBOX               1136
#define IDC_BUTTON_SKY3                 1137
#define IDC_BUTTON_SKY4                 1138
#define IDC_BUTTON_SKY5                 1139
#define IDC_BUTTON_SKY6                 1140
#define IDC_RADIO_SKY_SPHERE            1141
#define IDC_RADIO_SKY_BOX               1142
#define IDC_STATIC_SKY_TEX4             1143
#define IDC_STATIC_SKY_TEX5             1144
#define IDC_STATIC_SKY_TEX6             1145
#define IDC_PLANT_ADD_SORT              1146
#define IDC_PLANT_ADD                   1147
#define IDC_TREE_TYPES_ADD              1147
#define IDC_PLANT_DELETE                1148
#define IDC_PLANT_SAVE                  1149
#define IDC_PLANT_OPEN                  1150
#define IDC_PLANT_DELETE_FROM_TERRAIN   1151
#define IDC_TREE_PLANT_LIST             1152
#define IDC_PLANT_ADD_TO_TERRAIN        1153
#define IDC_EDIT_PLANTS_DENSITY         1154
#define IDC_EDIT_PLANTS_SCALE           1155
#define IDC_SPIN_PLANTS_SCALE           1156
#define IDC_SPIN_PLANTS_DENSITY         1157
#define IDC_PLANT_MOVE_Y                1158
#define IDC_SCENE_OBJECT_PATH           1159
#define IDC_PLANT_MOVE_XZ               1159
#define IDC_EDIT_GRASS_ALPHAREF         1160
#define IDC_EDIT_SUNDIRX                1161
#define IDC_SPIN_GRASS_ALPHAREF         1161
#define IDC_EDIT_SUNDIRY                1162
#define IDC_LOAD_BRUSH_RAW              1162
#define IDC_EDIT_GRASS_SIGHTRANGE       1162
#define IDC_EDIT_SUNDIRZ                1163
#define IDC_SPIN_GRASS_SIGHTRANGE       1163
#define IDC_EDIT_AMBIENT                1164
#define IDC_RADIO_XZ                    1164
#define IDC_EDIT_GRASS_SIZE             1164
#define IDC_EDIT_SUNCOLOR               1165
#define IDC_RADIO_XY                    1165
#define IDC_SPIN_GRASS_SIZE             1165
#define IDC_CHECK_GETPOS                1166
#define IDC_EDIT_GRASS_SIZEVAR          1166
#define IDC_SPIN_GRASS_SIZEVAR          1167
#define IDC_BUTTON_SPEEDTREE            1167
#define IDC_EDIT_GRASS_SOFT             1168
#define IDC_BUTTON_DDS                  1168
#define IDC_SPIN_GRASS_SOFT             1169
#define SCENE_OBJECT_MODEL_RELOAD       1169
#define IDC_EDIT_PLANT_NAME             1170
#define IDC_CHECK_SHOW_STATICOBJECT     1170
#define IDC_EDIT_GRASS_MAX_NUM          1171
#define IDC_CHECK_SHOW_LIGHT            1171
#define IDC_SPIN_GRASS_MAXNUM           1172
#define IDC_CHECK_SHOW_AUDIO            1172
#define IDC_CHECK_SHOW_BOXAREA          1173
#define IDC_EDIT_PLANT_RES              1173
#define IDC_CHECK_SHOW_DUMMY            1174
#define IDC_CHECK_SHOW_SPECIALLY        1175
#define IDC_CHECK_SHOW_WATER            1176
#define IDC_CHECK_SHOW_AIAREA           1177
#define IDC_CHECK_SHOW_PATH             1178
#define IDC_CHECK_SHOW_NPC_PATH         1178
#define IDC_BUTTON1                     1179
#define IDC_BROWSE                      1179
#define IDC_CHECK_SHOW_CRITTER_GROUP    1179
#define IDC_NEW_AI                      1179
#define IDC_BTN_EXPAIGEN                1179
#define IDC_BUTTON_TERRAIN_LINK         1179
#define IDC_MONSTER_TYPE                1179
#define IDC_BUTTON_FIND                 1179
#define IDC_BUTTON_CHANGE_VIEW_TYPE     1179
#define IDC_BUTTON_NULL                 1179
#define IDC_BUTTON_CHANGE_RES           1179
#define IDC_BUTTON_ADD_RES              1179
#define IDC_BUTTON_CHECK_OUT            1179
#define IDC_PATH_SELECT                 1179
#define IDC_TERRAIN_OBSTRUCT_MAP_SAVE   1179
#define IDC_PRECINCT_ADD_POS            1179
#define IDC_BUTTON_FRESH_SCENE_LIST     1179
#define IDC_BUTTON_RECREATE_CLOUD       1179
#define IDC_BUTTON_DAY                  1179
#define IDC_BUTTON_NEW_WORKSPACE        1179
#define IDC_BUTTON_BROWSE               1179
#define IDC_BUTTON_FINDER               1179
#define IDC_BUTTON_SEL_BRUSH            1179
#define IDC_BTN_SEARCH                  1179
#define IDC_MERGE                       1179
#define IDC_BTN_OK                      1179
#define IDC_BUTTON_SWITCH_PICK_ALL      1179
#define IDC_EDIT_WIDTH                  1180
#define IDC_CHECK_SHOW_SKINMODEL        1180
#define IDC_DELETE_AI                   1180
#define IDC_MONSTER_HELP                1180
#define IDC_BUTTON_DEL_RES              1180
#define IDC_TERRAIN_OBSTRUCT_MAP_TRANS  1180
#define IDC_BUTTON_RECREATE_GROUP       1180
#define IDC_BUTTON_NIGHT                1180
#define IDC_BUTTON_DEL_WORKSPACE        1180
#define IDC_BUTTON_FRESH_DEL_SCENE_OBJECT 1180
#define IDC_EDIT_HEIGHT                 1181
#define IDC_MODIFY_AI                   1181
#define IDC_MONSTER_FREND               1181
#define IDC_BUTTON_REPLACE_RES          1181
#define IDC_BUTTON_RECREATE_ALLGROUP    1181
#define IDC_TERRAIN_OBSTRUCT_MAP_SETSEED 1181
#define IDC_CHECK_SHOW_NON_NPC_PATH     1181
#define IDC_EDIT_ROW                    1182
#define IDC_CHECK_SHOW_FIXED_NPC        1182
#define IDC_BUTTON_UPDATE_RES           1182
#define IDC_SEL_PATH_BROWSE             1182
#define IDC_TERRAIN_OBSTRUCT2_MAP_TRANS 1182
#define IDC_EDIT_COL                    1183
#define IDC_LIST_AI                     1183
#define IDC_CHECK_SHOW_TERRAIN_BLOCK    1183
#define IDC_BUTTON_TRANS_OLD_MAP        1183
#define IDC_TERRAIN_OBSTRUCT_MAP_SPACE_CREATE 1183
#define IDC_RADIO_INITIACTIVE           1184
#define IDC_CHECK_SHOW_TREE             1184
#define IDC_BUTTON_RES_FIND             1184
#define IDC_TERRAIN_OBSTRUCT_SAVE_ALL_MAP 1184
#define IDC_RADIO_NOACTIVE              1185
#define IDC_CHECK_SHOW_GRASS            1185
#define IDC_TERRAIN_OBSTRUCT2_MAP_SETSEED 1185
#define IDC_CHECK_PICK_FIXEDNPC         1186
#define IDC_RADIO_NORMAL                1186
#define IDC_CHECK_SHOW_GATHER           1186
#define IDC_TERRAIN_OBSTRUCT2_SAVE_ALL_MAP 1186
#define IDC_CHECK_SHOW_TERRAIN          1187
#define IDC_TERRAIN_OBSTRUCT2_MAP_SETSEED2 1187
#define IDC_TERRAIN_OBSTRUCT2_MERGE     1187
#define IDC_CHECK3                      1188
#define IDC_CHECK_SHOW_RANGE            1188
#define IDC_BUTTON_PREVIEW              1189
#define IDC_MONSTER_DEFAULT_2           1189
#define IDC_CHECK_SHOW_INSTANCE_BOX     1189
#define IDC_RADIO_2                     1190
#define IDC_MONSTER_DEFAULT_3           1190
#define IDC_CHECK_SHOW_DYNAMIC          1190
#define IDC_RADIO_1                     1191
#define IDC_CHECK_SHOW_CLOUD            1191
#define IDC_STATIC_BITMAP               1192
#define IDC_CHECK_SHOW_CLOUD_LINE       1192
#define IDC_PROGRESS_LINK               1193
#define IDC_CHECK_SHOW_MONSTER_VIEW     1193
#define IDC_RADIO_LINK1                 1194
#define IDC_RADIO_LINK2                 1195
#define IDC_RADIO_HELP_NEED             1196
#define IDC_RADIO_HELP_NO               1197
#define IDC_MONSTER_DEFAULT_1           1198
#define IDC_MONSTER_FIND                1199
#define IDC_LIST1                       1200
#define IDC_LIST_MONSTER                1200
#define IDC_LIST_RES                    1200
#define IDC_MUSIC_LIST                  1200
#define IDC_GATHER_LIST                 1200
#define IDC_LIST_SERTCH_RESULT          1200
#define IDC_LIST_OBJECT_LIST            1200
#define IDC_LIST_DYNAMIC_OBJECT         1200
#define IDC_LIST_REPORT                 1200
#define IDC_LIST_PATH                   1200
#define IDC_BLOCK_VIEW                  1201
#define IDC_LIST_PRECINCT_NPC           1201
#define IDC_BUTTON_BLOCK_BLACK          1203
#define IDC_LIST_BEZIER                 1204
#define ID_UPDATEDATA                   1205
#define IDC_SELCOLOR                    1208
#define IDC_RADIO_DAY                   1209
#define IDC_RADIO_NIGHT                 1210
#define IDC_LIST_REF                    1212
#define IDC_PROGRESS_RES_EXP            1215
#define IDC_PROGRESS_MOVE               1217
#define ID_MUSIC_ADD                    1218
#define IDC_LIST_GATHER_OBJECT          1220
#define IDC_RADIO_SIZE512               1221
#define IDC_RADIO_SIZE1024              1222
#define IDC_CHECK_EXP_TERRAIN           1223
#define IDC_RADIO_SIZE256               1223
#define IDC_CHECK_EXP_OBJECT            1224
#define IDC_RADIO_NPC                   1224
#define IDC_RADIO_MONSTER               1225
#define IDC_SPIN_SPRITE_NUM             1226
#define IDC_SPIN_SPRITE_SIZE            1227
#define IDC_SPIN_SPRITE_DIST            1228
#define IDC_EDIT_HEIGHT1                1234
#define IDC_EDIT_HEIGHT2                1235
#define IDC_EDIT_HEIGHT3                1236
#define IDC_EDIT_HEIGHT4                1237
#define IDC_EDIT_HEIGHT5                1238
#define IDC_STATIC_COLOR1               1239
#define IDC_STATIC_COLOR2               1240
#define IDC_STATIC_COLOR3               1241
#define IDC_STATIC_COLOR4               1242
#define IDC_STATIC_COLOR5               1243
#define IDC_EDIT_GROUP_SPRITE_NUM       1244
#define IDC_EDIT_GROUP_SPRITE_SIZE      1245
#define IDC_SLIDER_TIME                 1246
#define IDC_LIST_WORKSPACE              1247
#define IDC_SLIDER_SFX                  1249
#define IDC_SLIDER_MUSIC                1250
#define IDC_BUTTON_RANGE_X              1251
#define IDC_BUTTON_RANGE_Y              1252
#define IDC_BUTTON_RANGE_Z              1253
#define IDC_BUTTON_RANGE_DIR            1254
#define IDC_PROGRESS_TOTAL              1254
#define IDC_EDIT_YEAR                   1255
#define IDC_EDIT_MOUTH                  1256
#define IDC_PROGRESS_PROCESS            1256
#define IDC_EDIT_DATE                   1257
#define ID_CHECK_OUT                    1257
#define IDC_LIST_DY_OBJ                 1258
#define IDC_STATIC_FLAG                 1259
#define IDC_LIST_CONTROLLER_OBJECT      1260
#define IDC_CHECK1_TIMEINVAILID         1261
#define IDC_CHECK2_TIMEINVAILID         1262
#define IDC_CHECK_ISACTIVEINIT          1263
#define IDC_EDIT_TIME_RANGE             1264
#define IDC_TAB_SORT                    1265
#define IDC_TREE_FILTER                 1266
#define IDC_COMBO_SET                   1267
#define IDC_BUTTON_SEL_COPY             1268
#define IDC_BUTTON2                     1269
#define IDC_BTN_LIST_ALL                1269
#define IDC_BTN_CHECKOUT                1269
#define IDC_BTN_SAVEMASK                1269
#define IDC_BUTTON_SWITCH_SHOW_ALL      1269
#define IDC_STATIC_GRID                 1270
#define IDC_EXPORT                      1271
#define IDC_SELECT_ALL                  1272
#define IDC_STATIC_MAP                  1272
#define IDC_UNSELECT_ALL                1273
#define IDC_RAD_TYPE                    1273
#define IDC_RAD_TYPE2                   1274
#define IDC_RAD_TYPE3                   1275
#define IDC_RAD_TYPE4                   1276
#define IDC_CHK_CONNECT3                1277
#define IDC_CHK_CONNECT4                1278
#define IDC_COL_1                       1279
#define IDC_COL_2                       1280
#define IDC_COL_3                       1281
#define IDC_COL_4                       1282
#define IDC_BTN_CHECKIN                 1283
#define IDC_RAD_TYPE5                   1284
#define IDC_RAD_TYPE6                   1285
#define IDC_COL_5                       1286
#define IDC_COL_6                       1287
#define IDC_RAD_TYPE7                   1288
#define IDC_COL_7                       1289
#define IDC_MAINLINE_MIN_LEN            1290
#define IDC_MAINLINE_MAX_LEN            1291
#define IDC_BRANCH_MIN_COUNT            1292
#define IDC_BRANCH_MAX_COUNT            1293
#define IDC_BRANCH_MIN_LEN              1294
#define IDC_BRANCH_MAX_LEN              1295
#define IDC_START_POSX                  1296
#define IDC_START_POSY                  1297
#define IDC_START_POSZ                  1298
#define IDC_EDIT_KEY                    1299
#define IDC_LIST_OBJECT                 1301
#define IDC_STATIC_COUNT                1302
#define ID_VF_VIEWXY                    32771
#define ID_VF_VIEWXZ                    32772
#define ID_VF_VIEWYZ                    32773
#define ID_VF_VIEWPERSPECTIVE           32774
#define ID_FILE_SAVEAS                  32775
#define ID_FILE_SETWORKDIR              32776
#define ID_HM_HM_NEW                    32777
#define ID_HM_HM_LOAD                   32778
#define ID_HM_EDIT_ERASE                32780
#define ID_HM_HM_HOLD                   32781
#define ID_HM_HM_FETCH                  32782
#define ID_TERRAIN_HEIGHTMAP            32783
#define ID_HM_HM_SAVE                   32784
#define ID_BUTTON32786                  32786
#define ID_BUTTON32787                  32787
#define ID_BUTTON32788                  32788
#define ID_BUTTON32789                  32789
#define ID_HM_VIEW_VIEWALL              32790
#define ID_TERRAIN_SURACES              32791
#define ID_VIEW_RESETCAMERA             32792
#define ID_VF_WIREFRAME                 32793
#define ID_FILE_EXPORTGAMEDATA          32795
#define ID_HM_EDIT_MAPPROP              32796
#define ID_LT_FILE_LOAD                 32797
#define ID_LT_FILE_SAVE                 32798
#define ID_TERRAIN_LIGHTING             32799
#define ID_TERRAIN_CREATESURFS          32800
#define ID_BUTTON32801                  32801
#define ID_BUTTON32802                  32802
#define ID_BUTTON32804                  32804
#define ID_BUTTON32806                  32806
#define ID_BUTTON32808                  32808
#define ID_BUTTON32809                  32809
#define ID_BUTTON32811                  32811
#define ID_BUTTON32812                  32812
#define ID_BRUSH_RADIUS_ADD             32812
#define ID_BUTTON32813                  32813
#define ID_BRUSH_RADIUS_SUB             32813
#define ID_BUTTON32814                  32814
#define ID_BRUSH_RADIUS_1               32814
#define ID_BUTTON32815                  32815
#define ID_BRUSH_RADIUS_2               32815
#define ID_BUTTON32816                  32816
#define ID_BRUSH_RADIUS_3               32816
#define ID_BUTTON32817                  32817
#define ID_BRUSH_RECT                   32817
#define ID_BUTTON32819                  32819
#define ID_BRUSH_CIRCLE                 32819
#define ID_BUTTON32827                  32827
#define ID_BUTTON32829                  32829
#define ID_OPERATION_UNDO               32830
#define ID_OPERATION_REDO               32831
#define ID_OPERATION_SELECT             32832
#define ID_OPERATION_MOVE               32833
#define ID_OPERATION_ROTATE             32834
#define ID_OPERATION_SELECTMULTI        32835
#define ID_OPERATION_SCALE              32837
#define ID_OPERATION_DELETE             32838
#define ID_SUF_FILE_LOAD                32839
#define ID_SUF_FILE_SAVE                32840
#define ID_BEZIER_ADDPOINT              32842
#define ID_BEZIER_SUBPOINT              32843
#define ID_BEZIER_CUT                   32844
#define ID_BEZIER_SMOOTH                32845
#define ID_BEZIER_DRAG                  32846
#define ID_BUTTON_NOSPEAK               32847
#define ID_BUTTON_SHOW_VERNIER          32848
#define ID_BEZIER_TEST                  32849
#define ID_EDIT_OBJECT_COPY             32850
#define ID_FILE_AUTOPARTHM              32852
#define ID_FILE_SORT_MAP                32853
#define ID_MAP_AUTO_MERGE               32854
#define ID_TERRAIN_MODIFIED_PROFILE     32855
#define ID_OPERATION_OBSTRUCT           32856
#define ID_BEZIER_MERGE                 32857
#define ID_EXP_AI_DATA                  32858
#define ID_IMP_AI_DATA                  32859
#define ID_TERRAIN_BLOCK_VIEW           32860
#define ID_DAY_NIGHT                    32861
#define ID_BUTTON_RAIN                  32862
#define ID_BUTTON_SNOW                  32864
#define ID_MENU_RES_MAN                 32867
#define ID_SET_VSS                      32868
#define ID_GET_VSS_ALL                  32869
#define VSS_TEST_MAP_CHECKIN            32871
#define ID_EXPORT_GAME_RES              32872
#define ID_MOVE_ALL_SCENE_OBJECT        32873
#define ID_GET_ALL_MAP_DATA             32874
#define ID_EXP_TOPVIEW_MAP              32877
#define ID_OPERATION_TEST_BEIZER_INTERSECT 32878
#define ID_TEST_PRECINCT                32879
#define ID_TEST_PRECINCT_ERROR          32880
#define ID_SHOW_MODEL_PLANE             32881
#define ID_MERGE_TREE_TYPE              32882
#define ID_ROTATE_X                     32883
#define ID_ROTATE_Y                     32884
#define ID_ROTATE_Z                     32885
#define ID_SHOW_SEL_ONLY                32892
#define ID_SET_WORKSPACE                32893
#define ID_SHOW_TERRAIN_LIGHT           32895
#define ID_SHOW_DISTANCE                32896
#define ID_INSERT_MOUNSTER_TO_MAP       32897
#define ID_GET_CURRENT_PROJ_WORKSPACE_MAPS 32898
#define ID_MOUNSTER_STAT                32899
#define ID_MODEL_CHANGED                32900
#define ID_EXPORT_SKY_INFOR             32902
#define ID_EXP_LIGHT_INFOR_LIST         32903
#define ID_DYNAMIC_OBJECT_EDITOR        32904
#define ID_MONSTER_CONTROLLER_EDITOR    32905
#define ID_RELOAD_ALL_TEXTURES          32906
#define ID_EXPORT_STAT_NPCS             32907
#define ID_OPERATION_ROTATE2            32908
#define ID_STAT_ALL_TRIANGLE            32909
#define ID_STATUS_TRIANGLE_SEL          32910
#define ID_OBJECT_DROP                  32911
#define ID_SET_TO_TREE                  32912
#define ID_TRANLATE_MAP_TO_PW           32913
#define ID_EXPORT_COORD_DATA            32914
#define ID_FILE_EXPORT_SERVER_BHT_BY_PROJECT 32915
#define ID_FILE_EXPORT_PATH_INFO        32916
#define ID_FILE_RANDOM_MAP_INFO         32917
#define ID_SELECT_BY_ID                 32918
#define ID_INDICATOR_EDIT_X             0xE700
#define ID_INDICATOR_EDIT_Z             59143
#define ID_INDICATOR_STATIC_X           59144
#define ID_INDICATOR_STATIC_Y           59145
#define ID_INDICATOR_STATIC_Z           59146
#define ID_INDICATOR_EDIT_Y             59147
#define ID_INDICATOR_BRUSH_RADIUS       59148
#define ID_INDICATOR_COMBO              59149
#define ID_INDICATOR_PROGRESS           59150

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        257
#define _APS_NEXT_COMMAND_VALUE         32919
#define _APS_NEXT_CONTROL_VALUE         1303
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
