/*
 * FILE: EC_MsgDef.h
 *
 * DESCRIPTION: 
 *
 * CREATED BY: Duyuxin, 2004/8/30
 *
 * HISTORY: 
 *
 * Copyright (c) 2004 Archosaur Studio, All Rights Reserved.
 */

#pragma once

///////////////////////////////////////////////////////////////////////////
//	
//	Define and Macro
//	
///////////////////////////////////////////////////////////////////////////

//	Fixed message define
enum
{
	FIXMSG_PICKUPMONEY = 0,		//	0
	FIXMSG_GOTEXP,
	FIXMSG_LOSTEXP,
	FIXMSG_LEVELUP,
	FIXMSG_GOTSP,

	FIXMSG_PICKUPITEM,			//	5
	FIXMSG_LEAVETEAM,
	FIXMSG_KICKEDOUTTEAM,
	FIXMSG_CANCELTEAM,
	FIXMSG_JOINTEAM,
	
	FIXMSG_REJECTJOINTEAM,		//	10
	FIXMSG_TEAMMEMPICKUP,
	FIXMSG_CHAT,
	FIXMSG_PRIVATECHAT1,
	FIXMSG_PRIVATECHAT2,

	FIXMSG_GAINITEM,			//	15
	FIXMSG_PRODUCEITEM,
	FIXMSG_MISSED,
	FIXMSG_DISCONNECTED,
	FIXMSG_NOTARGET,

	FIXMSG_TARGETISFAR,			//	20
	FIXMSG_TEAMMEMKICKEDOUT,
	FIXMSG_WRONGVERSION,
	FIXMSG_OFFLINE,
	FIXMSG_DODAMAGE,

	FIXMSG_BEDAMAGED,			//	25
	FIXMSG_INVALIDWEAPON,
	FIXMSG_TARGETWRONG,
	FIXMSG_WRONGCUSTOMDATA,
	FIXMSG_SEARCHTEAM,

	FIXMSG_SEARCHTEAMMEM,		//	30
	FIXMSG_LEVELANDPROF,
	FIXMSG_PROF_WARRIOR,
	FIXMSG_PROF_MAGE,
	FIXMSG_PROF_MONK,

	FIXMSG_PROF_HAG,			//	35
	FIXMSG_PROF_ORC,
	FIXMSG_PROF_GHOST,
	FIXMSG_PROF_ARCHOR,
	FIXMSG_PROF_ANGEL,
	
	FIXMSG_PACKFULL1,			//	40
	FIXMSG_PACKFULL2,
	FIXMSG_NOTTRADEITEM,
	FIXMSG_NEEDTOOL,
	FIXMSG_GOTREP,
	
	FIXMSG_LEVEL2_01,
	FIXMSG_LEVEL2_02,
	FIXMSG_LEVEL2_03,
	FIXMSG_LEVEL2_04,
	FIXMSG_LEVEL2_05,

	FIXMSG_LEVEL2_06,			//	50
	FIXMSG_LEVEL2_07,
	FIXMSG_LEVEL2_08,
	FIXMSG_LEVEL2_09,
	FIXMSG_LEVEL2_20,

	FIXMSG_LEVEL2_21,
	FIXMSG_LEVEL2_22,
	FIXMSG_LEVEL2_30,
	FIXMSG_LEVEL2_31,
	FIXMSG_LEVEL2_32,

	FIXMSG_LEVEL2UP,			//	60
	FIXMSG_PACKISFULL,
	FIXMSG_FAILEDTOCONN,
	FIXMSG_ENTERSHELTER,
	FIXMSG_LEAVESHELTER,
	
	FIXMSG_KICKOUTROLE,
	FIXMSG_KICKOUTUSER,
	FIXMSG_ONLINENUMBER,
	FIXMSG_RESTARTSEV,
	FIXMSG_SHUTUPROLE,
	
	FIXMSG_SHUTUPUSER,			//	70
	FIXMSG_NEEDMONEY,
	FIXMSG_SCREENSHOT,
	FIXMSG_NEEDMP,
	FIXMSG_MYFRIEND,

	FIXMSG_MSGSENDFAIL,
	FIXMSG_MSGSENDWAIT,
	FIXMSG_OPTSUCCESS,
	FIXMSG_OFFLINE2,
	FIXMSG_OPTOVERTIME,

	FIXMSG_REFUSEFRIEND,		//	80
	FIXMSG_GENDER_MALE,
	FIXMSG_GENDER_FEMALE,
	FIXMSG_NEWWAYPOINT,
	FIXMSG_BOOTHSELL,

	FIXMSG_BOOTHBUY,			//	85
	FIXMSG_FRIEND_OT,			//	Add friend overtime
	FIXMSG_SERVERCLOSE,
	FIXMSG_WRONGROLE,
	FIXMSG_SKILLINTERRUPT,
	
	FIXMSG_LOSEITEM,			//	90
	FIXMSG_ITEMDISAPPEAR,
	FIXMSG_ERR_FC_NETWORKERR,
	FIXMSG_ERR_FC_INVALID_OPERATION,
    FIXMSG_ERR_FC_OP_TIMEOUT,

    FIXMSG_ERR_FC_CREATE_ALREADY,	//	95
    FIXMSG_ERR_FC_CREATE_DUP,
    FIXMSG_ERR_FC_DBFAILURE,
    FIXMSG_ERR_FC_NO_PRIVILEGE,
    FIXMSG_ERR_FC_INVALIDNAME,

    FIXMSG_ERR_FC_FULL,				//	100
    FIXMSG_ERR_FC_APPLY_REJOIN,
    FIXMSG_ERR_FC_JOIN_SUCCESS,
    FIXMSG_ERR_FC_JOIN_REFUSE,
    FIXMSG_ERR_FC_ACCEPT_REACCEPT,

    FIXMSG_ERR_FC_FACTION_NOTEXIST,	//	105
    FIXMSG_ERR_FC_NOTAMEMBER,
    FIXMSG_ERR_FC_CHECKCONDITION,
    FIXMSG_ERR_FC_DATAERROR,
	FIXMSG_FC_CREATE,

	FIXMSG_FC_ACCEPT_JOIN,			//	110
	FIXMSG_FC_EXPEL,
	FIXMSG_FC_RESIGN,
	FIXMSG_FC_APPOINT,
	FIXMSG_FC_LEAVE,

	FIXMSG_FC_DISMISS,				//	115
	FIXMSG_FC_RENAME,
	FIXMSG_FC_CHG_PROCLAIM,
	FIXMSG_ERR_INSTDATA,
	FIXMSG_NEEDAP,
	
	FIXMSG_ITEM_CANNOTUSE,			//	120
	FIXMSG_ITEM_INCOOLTIME,
	FIXMSG_CMD_INCOOLTIME,
	FIXMSG_ADDMAXAP,
	FIXMSG_TRASHBOX_EXPAND,

	FIXMSG_FC_UPGRADE,				//	125
	FIXMSG_FC_DEGRADE,
	FIXMSG_ERR_FC_OFFLINE,
	FIXMSG_SKILL_INVALIDSTATE,
	FIXMSG_BEKILLED,
	
	FIXMSG_NOTENOUGHAMMO,			//	130
	FIXMSG_LEVELTOOLOW,
	FIXMSG_CHAT2,
	FIXMSG_FORBIDTIME,
	FIXMSG_FORBIDLOGIN,

	FIXMSG_FORBIDTALK,				//	135
	FIXMSG_FORBIDTRADE,
	FIXMSG_FORBIDSELL,
	FIXMSG_FORBIDREASON,
	FIXMSG_DUEL_WIN,

	FIXMSG_DUEL_DRAW,				//	140
	FIXMSG_DUEL_INFIGHT,
	FIXMSG_DUEL_ASKSENT,
	FIXMSG_WRONGPROF,
	FIXMSG_PET_HATCH,

	FIXMSG_PET_FREE,				//	145
	FIXMSG_PET_CORRALFULL,
	FIXMSG_FCRANK_MASTER,
	FIXMSG_FCRANK_VICEMASTER,
	FIXMSG_FCRANK_BODYGUARD,

	FIXMSG_FCRANK_POINEER,			//	150
	FIXMSG_FCRANK_MEMBER,
	FIXMSG_SERVERUPDATE,
	FIXMSG_BAT_INVADER_WIN,
	FIXMSG_BAT_DEFENDER_WIN,

	FIXMSG_OBTAINTANK,				//	155
	FIXMSG_LOSETANK,
	FIXMSG_PET_DEAD,
	FIXMSG_GM_INVISIBLE,
	FIXMSG_GM_VISIBLE,

	FIXMSG_GM_INVINCIBLE,			//	160
	FIXMSG_GM_VINCIBLE,
	FIXMSG_BEDAMAGED2,
	FIXMSG_WHOSETHING,
	FIXMSG_PET_LEVELUP,

	FIXMSG_ITEMEXPIRED,				//	165
	FIXMSG_ERR_GSHOPDATA,
	FIXMSG_ITEMBOUND,
	FIXMSG_NEW_INVENTORY_SIZE,
	FIXMSG_PET_ROOM_SIZE,

	FIXMSG_FC_ACCEPT_JOIN2,			//	170
	FIXMSG_GOTDIVORCED,
	FIXMSG_GOTMARRIED,
	FIXMSG_TRASHBOX2_EXPAND,
	FIXMSG_TRASHBOX3_EXPAND,
	
	FIXMSG_GOBLIN_FORGET_SKILL,		//  175
	FIXMSG_GOBLIN_REFINE_SUCC,
	FIXMSG_GOBLIN_REFINE_FAIL,
	FIXMSG_GOBLIN_DESTROY,
	FIXMSG_GOBLIN_LEARN_SKILL,

	FIXMSG_GOBLIN_LEVELUP,			//	180
	FIXMSG_GOBLIN_GET_GENIUS,
	FIXMSG_GOBLIN_GET_STATUSPT,
	FIXMSG_GOBLIN_GET_EXTRA_PT,	
	FIXMSG_GOBLIN_TRADE_FAIL,	

	FIXMSG_GOBLIN_WASHPT_STR,		//	185
	FIXMSG_GOBLIN_WASHPT_AGI,
	FIXMSG_GOBLIN_WASHPT_VIT,
	FIXMSG_GOBLIN_WASHPT_ENG,
	FIXMSG_GOBLIN_TRADE_FAIL_2,

	FIXMSG_GOBLIN_DESTROY_EXP_0,	//  190
	FIXMSG_GOBLIN_DESTROY_EQUIP,
	FIXMSG_GOBLIN_NEED_MP,
	FIXMSG_GOBLIN_NEED_AP,
	FIXMSG_GOBLIN_CAST_SKILL_FAIL,

	FIXMSG_GOBLIN_ACTIVE_FAIL,		//  195
	FIXMSG_GOBLIN_IS_FIGHTING,
	FIXMSG_GOBLIN_SKILL_COOLING,
	FIXMSG_GOBLIN_OPT_COOLING,
	FIXMSG_GOBLIN_EQUIP_REMOVE,
	
	FIXMSG_GOBLIN_EQUIP_REPLACE,	//  200
	FIXMSG_GOBLIN_GROUND_ONLY,
	FIXMSG_GOBLIN_AIR_ONLY,
	FIXMSG_GOBLIN_AIR_GROUND_ONLY,
	FIXMSG_GOBLIN_WATER_ONLY,	

	FIXMSG_GOBLIN_GROUND_WATER_ONLY, //  205
	FIXMSG_GOBLIN_AIR_WATER_ONLY,
	FIXMSG_GOBLIN_WRONG_PROF,
	FIXMSG_GOBLIN_GENIUSPT_WASHED,
	FIXMSG_GOBLIN_GET_STAMINA,	

	FIXMSG_OBJECT_NOT_IN_INSTANCE,	//	210
	FIXMSG_ITEM_UNREPAIRABLE,
	FIXMSG_CANNOT_USE_IN_BATTLE,
	FIXMSG_CANNOT_USE_IN_CURR_MAP,
	FIXMSG_CANNOT_AUTO_FASHION_WHEN_BOOTH,

	FIXMSG_FASHION_PACK_EMPTH,		//  215
	FIXMSG_FASHION_SC_EMPTY,
	FIXMSG_FASHION_PACK_FULL,
	FIXMSG_SKILL_INVALIDENV,
	FIXMSG_EQUIP_DESTROYING, 

	FIXMSG_ENTER_INVISIBLE_STATE,	//	220
	FIXMSG_LEAVE_INVISIBLE_STATE,
	FIXMSG_PERFECT_WORLD,
	FIXMSG_CANNOT_AUCTION_WHEN_DESTROY,
	FIXMSG_ACCBOX_EXPAND,

	FIXMSG_CANNOT_USE_WHEN_INVISIBLE,	//	225
	FIXMSG_PRODUCE_LEVEL_INVALID,
	FIXMSG_PRODUCE_ABILITY_FULL,
	FIXMSG_GOTSCORE,
	FIXMSG_PROF_JIANLING,
	
	FIXMSG_PROF_MEILING,				//	230
	FIXMSG_NEEDITEM,
	FIXMSG_CANNOT_SHARPEN_SLOT,
	FIXMSG_SHARPEN_ON_DRAG,
	FIXMSG_SUMMON_PET_APPEAR,
	
	FIXMSG_SUMMON_PET_DISAPPEAR,		//	235
	FIXMSG_FACTION_EXP_CONTRIB_INCREASE,
	FIXMSG_FACTION_EXP_CONTRIB_DECREASE,
	FIXMSG_FACTION_CONSUME_CONTRIB_INCREASE,
	FIXMSG_FACTION_CONSUME_CONTRIB_DECREASE,
	
	FIXMSG_DIVIDEND_INCREASE,	//	240
	FIXMSG_DIVIDEND_DECREASE,
	FIXMSG_HP_UNSATISFIED,
	FIXMSG_GM_REMOVESPECITEM,
	FIXMSG_GOTFORCECON,

	FIXMSG_LOSTFORCECON,	//	245
	FIXMSG_GOTFORCEREP,
	FIXMSG_LOSTFORCEREP,
	FIXMSG_JOINFORCE,
	FIXMSG_QUITFORCE,

	FIXMSG_TARGETISNEAR,		//	250
	FIXMSG_WOULD_STUCK_OR_SO,
	FIXMSG_TASK_LIMIT_INCREASED,
	FIXMSG_GAIN_SKILL,
	FIXMSG_LOSE_SKILL,

	FIXMSG_PET_ENTERSHELTER,	// 255
	FIXMSG_PET_LEAVESHELTER,
	FIXMSG_COUNTRY_INVADER_WIN,
	FIXMSG_COUNTRY_DEFENDER_WIN,
	FIXMSG_OR_STRING,

	FIXMSG_USE_IN_SANCTUARY_ONLY,	//	260
	FIXMSG_OBSOLETE_ROLENAME,
	FIXMSG_FC_EXPEL2,
	FIXMSG_FC_DELAYEXPEL,
	FIXMSG_FC_DELAYEXPEL2,

	FIXMSG_FC_DELAYEXPEL3,		//	265
	FIXMSG_FC_CANCELEXPEL,
	FIXMSG_FC_CANCELEXPEL2,
	FIXMSG_REBUILD_PET_IN_SANCTUARY_ONLY,
	FIXMSG_GOT_REALMEXP,

	FIXMSG_GOT_BOOKEXP,			//	270
	FIXMSG_RAND_SHOP_INVALID_CONFIG,
	FIXMSG_RAND_SHOP_INVALID_ROLE_STATE,
	FIXMSG_RAND_SHOP_INVALID_OP,
	FIXMSG_NEEDCASH,

	FIXMSG_INLOCK,				//	275
	FIXMSG_FACTION_PVP_GETRANK_ERROR_TIME,
	FIXMSG_FACTION_PVP_GETRANK_PERMISSION_DENIED,
	FIXMSG_ERR_FC_INVALID_IN_PVP,
	FIXMSG_FACTION_PVP_GOT_SCORE_FOR_MINECAR,

	FIXMSG_FACTION_PVP_GOT_SCORE_FOR_MINEBASE,	//	280
	FIXMSG_GOT_WORLD_CONTRIBUTION,
	FIXMSG_PROF_YEYING,
	FIXMSG_PROF_YUEXIAN,
	FIXMSG_REMIND_RECONNECT,
	
	FIXMSG_INVALID_NAME_LEN,
	FIXMSG_FC_RENAME_FACTION,
};

//	Description define
enum
{
	//	Item description ...
	ITEMDESC_ATKSPD_VERYSLOW = 0,		//	0, Attack speed
	ITEMDESC_ATKSPD_SLOW,
	ITEMDESC_ATKSPD_NORMAL,
	ITEMDESC_ATKSPD_FAST,
	ITEMDESC_ATKSPD_VERYFAST,

	ITEMDESC_COL_LIGHTBLUE,
	ITEMDESC_COL_YELLOW,
	ITEMDESC_COL_PURPLE,
	ITEMDESC_COL_DARKGOLD,
	ITEMDESC_COL_WHITE,

	ITEMDESC_COL_GRAY,
	ITEMDESC_COL_BLUE,
	ITEMDESC_COL_GREEN,
	ITEMDESC_COL_RED,
	ITEMDESC_COL_CYANINE,

	ITEMDESC_NAMESOCKET,				//	15, name (socket num)
	ITEMDESC_CLASSNAME,					//	Item class name
	ITEMDESC_ATKSPEED,					//	Attack speed
	ITEMDESC_PHYDAMAGE,
	ITEMDESC_MAGICDAMAGE,

	ITEMDESC_ENDURANCE,					//	20
	ITEMDESC_LEVELREQ,
	ITEMDESC_STRENGTHREQ,
	ITEMDESC_AGILITYREQ,
	ITEMDESC_PRICE,

	ITEMDESC_PHYDEFENCE,
	ITEMDESC_GOLDDEFENCE,
	ITEMDESC_WOODDEFENCE,
	ITEMDESC_WATERDEFENCE,
	ITEMDESC_FIREDEFENCE,

	ITEMDESC_EARTHDEFENCE,
	ITEMDESC_NAMENUMBER,				//	name (number)
	ITEMDESC_REMAINTIME,				//	Remained time
	ITEMDESC_NAME,
	ITEMDESC_ADDPHYDAMAGE,

	ITEMDESC_ADDMAGICDAMAGE,
	ITEMDESC_DODGE,
	ITEMDESC_ADDHP,
	ITEMDESC_ADDMP,
	ITEMDESC_NOTDEAL,

	ITEMDESC_WEAPONREQ,					//	40
	ITEMDESC_TASKITEM,
	ITEMDESC_ATKDISTANCE,				//	Attack distance
	ITEMDESC_PHYDEFEXTRA,
	ITEMDESC_RUNSPEEDEXTRA,

	ITEMDESC_DODGEEXTRA,
	ITEMDESC_PHYRESIST,
	ITEMDESC_HPRECOVER,
	ITEMDESC_MPRECOVER,
	ITEMDESC_ATKTIME,

	ITEMDESC_CASTTIME,
	ITEMDESC_DEADLYSTRIKE,
	ITEMDESC_FIREWORKTIME,
	ITEMDESC_PETLEVEL,
	ITEMDESC_ATKRATINGEXTRA,

	ITEMDESC_EXP,
	ITEMDESC_RANDOMPROP,				
	ITEMDESC_PHYDMGEXTRA,
	ITEMDESC_MAGICDMGEXTRA,
	ITEMDESC_CASTSKILL,

	ITEMDESC_MAXPHYDAMAGE,				//  60
	ITEMDESC_MAXMAGICDAMAGE,
	ITEMDESC_ENDURANCEEXTRA,
	ITEMDESC_REQEXTRA,
	ITEMDESC_ALLMAGICDEF,

	ITEMDESC_GOLDDEFEXTRA,
	ITEMDESC_WOODDEFEXTRA,
	ITEMDESC_WATERDEFEXTRA,
	ITEMDESC_FIREDEFEXTRA,
	ITEMDESC_EARTHDEFEXTRA,

	ITEMDESC_HPEXTRA,
	ITEMDESC_MPEXTRA,
	ITEMDESC_ADDATKDIST,
	ITEMDESC_PROJECTILE,
	ITEMDESC_ATKRATING,

	ITEMDESC_2STRINGS,
	ITEMDESC_ADDHPINTIME,	
	ITEMDESC_ADDMPINTIME,	
	ITEMDESC_DECHALFPOISON,	
	ITEMDESC_ANTIDOTE,		

	ITEMDESC_ALLMAGICRESIST,			//  80
	ITEMDESC_USEEFFECT,
	ITEMDESC_RECRUITHP,
	ITEMDESC_RECRUITMP,
	ITEMDESC_RECRUITHPMP,

	ITEMDESC_LEVEL,
	ITEMDESC_USEREQUIREMENT,
	ITEMDESC_MAXLEVELREQ,
	ITEMDESC_WEAPONLVLREQ,
	ITEMDESC_ELEMENTTIME,

	ITEMDESC_ADDFLYSPEED,
	ITEMDESC_MPCONSUME,
	ITEMDESC_PROFESSIONREQ,
	ITEMDESC_RUNSPEED,
	ITEMDESC_GENDERREQ,

	ITEMDESC_ERRORITEM,
	ITEMDESC_COLOR,
	ITEMDESC_PENTAGON,
	ITEMDESC_COLORRECT,
	ITEMDESC_UNITPRICE,
	
	ITEMDESC_REPAIRCOST,			//	100	
	ITEMDESC_VALIDTIME,
	ITEMDESC_VITALITYREQ,
	ITEMDESC_ENERGYREQ,
	ITEMDESC_ERRORPROP,
	
	ITEMDESC_STRENGTH,
	ITEMDESC_AGILITY,
	ITEMDESC_VITALITY,
	ITEMDESC_ENERGY,
	ITEMDESC_CASTSKILL2,

	ITEMDESC_ADDFLYSPEED2,
	ITEMDESC_MADEFROM,
	ITEMDESC_WEAKDIST,
	ITEMDESC_FOODTYPE,
	ITEMDESC_FOOD_GRASS,

	ITEMDESC_FOOD_MEAT,
	ITEMDESC_FOOD_VEGETABLE,
	ITEMDESC_FOOD_FRUIT,
	ITEMDESC_FOOD_WATER,
	ITEMDESC_MOVESPEED,

	ITEMDESC_DAMAGE,				//	120		
	ITEMDESC_ATTACKRATE,
	ITEMDESC_PETSKILL,
	ITEMDESC_NULL02,
	ITEMDESC_NULL03,
	
	//	Command description ...
	CMDDESC_SITDOWN,
	CMDDESC_WALKRUN,
	CMDDESC_NORMALATTACK,
	CMDDESC_FINDTARGET,
	CMDDESC_ASSISTATTACK,

	CMDDESC_INVITETOTEAM,
	CMDDESC_LEAVETEAM,
	CMDDESC_KICKTEAMMEM,
	CMDDESC_FINDTEAM,
	CMDDESC_STARTTRADE,

	CMDDESC_SELLBOOTH,
	CMDDESC_BUYBOOTH,
	CMDDESC_INVITETOFACTION,
	CMDDESC_FLY,
	CMDDESC_PICKUP,

	CMDDESC_GATHER,					//	140	
	CMDDESC_RUSHFLY,
	CMDDESC_BINDBUDDY,
	CMDDESC_SKILLGROUP,
	CMDDESC_NULL3,

	//	Emotion description ...
	FACEDESC_WAVEHAND,
	FACEDESC_NOD,
	FACEDESC_SHADEHEAD,
	FACEDESC_SHRUG,
	FACEDESC_LAUGH,

	FACEDESC_ANGRY,	
	FACEDESC_FAINT,
	FACEDESC_SAD,
	FACEDESC_KISSHAND,
	FACEDESC_SHY,	

	FACEDESC_SALUTE,
	FACEDESC_SITDOWN,	
	FACEDESC_CHARGE,	
	FACEDESC_THINK,		
	FACEDESC_CHALLENGE,

	FACEDESC_WIN,					//	160	
	FACEDESC_GAPE,
	FACEDESC_KISS,
	FACEDESC_FIGHT,
	FACEDESC_ATTACK1,

	FACEDESC_ATTACK2,
	FACEDESC_ATTACK3,
	FACEDESC_ATTACK4,
	FACEDESC_DEFENCE,
	FACEDESC_FALL,

	FACEDESC_FALLONGROUND,			//	170
	FACEDESC_LOOKAROUND,
	FACEDESC_DANCE,
	FACEDESC_FASHIONWEAPON, 
	FACEDESC_NULL01,

	ITEMDESC_EXPIRETIME_DAY,
	ITEMDESC_EXPIRETIME_HOUR_MIN,
	ITEMDESC_EXPIRETIME_MIN_SEC,
	ITEMDESC_EXPIRETIME_SECOND,
	ITEMDESC_REFINETICKET1,

	ITEMDESC_REFINETICKET2,			//  180
	ITEMDESC_DESTROYINGNAME,
	ITEMDESC_EQUIP_BIND,
	ITEMDESC_AUTOHP1,
	ITEMDESC_AUTOHP2,

	ITEMDESC_AUTOMP1,
	ITEMDESC_AUTOMP2,
	ITEMDESC_COOLTIME,
	ITEMDESC_DOUBLEEXP_TIME,
	ITEMDESC_EQUIP_BINDAFTERUSE,

	ITEMDESC_COL2_START,			//	190
	ITEMDESC_COL2_BLUEGREEN,
	ITEMDESC_COL2_RED,
	ITEMDESC_COL2_BRIGHTBLUE,
	ITEMDESC_COL2_NULL02,

	ITEMDESC_COL2_NULL03,
	ITEMDESC_COL2_NULL04,
	ITEMDESC_COL2_NULL05,
	ITEMDESC_COL2_NULL06,
	ITEMDESC_COL2_NULL07,

	ITEMDESC_SPOUSE_MALE,			//	200
	ITEMDESC_SPOUSE_FEMALE,
	ITEMDESC_ATK_DEGREE,
	ITEMDESC_DEF_DEGREE,
	ITEMDESC_GOBLIN_REFINE_LEVEL,
	
	ITEMDESC_GOBLIN_LEVEL,
	ITEMDESC_GOBLIN_RANDPT,
	ITEMDESC_GOBLIN_ENERGY,
	ITEMDESC_GOBLIN_ENERGY_RESTORE,
	ITEMDESC_GOBLIN_STAMINA,

	ITEMDESC_GOBLIN_REFINE_EFFECT,	//  210
	ITEMDESC_GOBLIN_TRADE_PROTECT,
	ITEMDESC_GOBLIN_TRADE_UNPROTECT,
	ITEMDESC_GOBLIN_CANTRADE,
	ITEMDESC_EXPPILL_EXP,
	
	ITEMDESC_GOBLINEQUIP_POS,
	ITEMDESC_GOBLINEQUIP_LEVELREQ,
	ITEMDESC_GOBLINEQUIP_GOLD,
	ITEMDESC_GOBLINEQUIP_WOOD,
	ITEMDESC_GOBLINEQUIP_WATER,

	ITEMDESC_GOBLINEQUIP_FIRE,		//  220
	ITEMDESC_GOBLINEQUIP_EARTH,
	ITEMDESC_GOBLINEQUIP_POS_1,
	ITEMDESC_GOBLINEQUIP_POS_2,
	ITEMDESC_GOBLINEQUIP_POS_3,

	ITEMDESC_GOBLINEQUIP_POS_4,	
	ITEMDESC_HASRANDOM_PROP,	
	ITEMDESC_GOBLIN_GROW_DEGREE,
	ITEMDESC_SPECIAL_PROP,
	ITEMDESC_DEAD_PROTECT,
	
	ITEMDESC_NO_DROP,				//	230
	ITEMDESC_NO_TRADE,
	ITEMDESC_NO_PLAYER_TRADE,
	ITEMDESC_LEAVE_SCENE_DISAPEAR,
	ITEMDESC_USE_AFTER_PICK_UP,

	ITEMDESC_DROP_WHEN_DEAD,
	ITEMDESC_DROP_WHEN_OFFLINE,	
	ITEMDESC_SELL_COL_NUM,
	ITEMDESC_BUY_COL_NUM,
	ITEMDESC_MAX_BOOTH_NAME,
	
	ITEMDESC_UNREPAIRABLE,			//	240
	ITEMDESC_TYPE,
	ITEMDESC_ATTACK_ITEM,
	ITEMDESC_DEFENCE_ITEM,
	ITEMDESC_BATTLE_ITEM,

	ITEMDESC_USE_REGION,
	ITEMDESC_CONSUME_COUNT,
	ITEMDESC_SKILL_EFFECT,
	ITEMDESC_SPECIAL_DESC,
	ITEMDESC_CONSUME_ANYWAY,

	ITEMDESC_USE_EFFECT,			//	250
	ITEMDESC_CANNOT_USE_IN_BATTLE,
	ITEMDESC_EQUIP_DESTROYING,
	ITEMDESC_EQUIP_REPAIR_NEED_ITEM,
	ITEMDESC_EQUIP_REPAIR_NEED_ITEMCNT,
	
	ITEMDESC_TOTAL_DEFENCE_ADD,
	ITEMDESC_NO_USER_TRASH,
	ITEMDESC_INC_SKILL_ABILITY_REQUIRE_LEVEL,
	ITEMDESC_INC_SKILL_ABILITY_RATIO,
	ITEMDESC_REPUTATION_REQ,

	ITEMDESC_ADDDAMAGE,				// 260
	ITEMDESC_PROFVIEW,
	ITEMDESC_WEDDING_BOOKCARD,
	ITEMDESC_WEDDING_INVITECARD,
	ITEMDESC_SOULPOWER,

	ITEMDESC_LASTTIME_DAY,
	ITEMDESC_LASTTIME_HOUR_MIN,
	ITEMDESC_LASTTIME_MIN_SEC,
	ITEMDESC_LASTTIME_SECOND,
	ITEMDESC_GOLDRESIST,

	ITEMDESC_WOODRESIST,			//	270
	ITEMDESC_WATERRESIST,
	ITEMDESC_FIRERESIST,
	ITEMDESC_EARTHRESIST,
	ITEMDESC_CAN_WEBTRADE,
	
	ITEMDESC_PRICE_SEPERATOR,	//	271
	ITEMDESC_PENETRATION,
	ITEMDESC_RESILIENCE,
	ITEMDESC_FORCE_REQUIRE,
	ITEMDESC_FORCE_REPU_TOTAL,

	ITEMDESC_FORCE_REPU_INC_RATIO,	//	280
	ITEMDESC_EQUIP_BIND_ONLY,
	ITEMDESC_REQUIRE_MAX_LEVEL,
	ITEMDESC_DEFENCE,
	ITEMDESC_ONE_HANDED_WEAPON,

	ITEMDESC_TWO_HANDED_WEAPON,	
	ITEMDESC_TWO_HANDED_POLEARM,
	ITEMDESC_TWO_HANDED_HEAVY,
	ITEMDESC_TWO_HANDED_POLEHEAVY,
	ITEMDESC_WHIP,

	ITEMDESC_BOW,					//  290
	ITEMDESC_CROSSBOW,
	ITEMDESC_BOXING_GLOVES,
	ITEMDESC_PIKE,
	ITEMDESC_EMPTY_HANDED,

	ITEMDESC_DAGGER,				// 295
	ITEMDESC_TALISMAN,
	ITEMDESC_EQUIPMARK,
	ITEMDESC_PET_EVO_NAME,
	ITEMDESC_PET_ATK_INHERIT,

	ITEMDESC_PET_DEF_INHERIT,			// 300
	ITEMDESC_PET_HP_INHERIT,
	ITEMDESC_PET_ATKLVL_INHERIT,
	ITEMDESC_PET_DEFLVL_INHERIT,
	ITEMDESC_PET_NATURE,

	ITEMDESC_CROSSSERVER_ERROR,		//	305
	ITEMDESC_USE_IN_SANCTUARY_ONLY,
	ITEMDESC_SYSMODULE_FM_GT, // GT
	ITEMDESC_SYSMODULE_FM_TOUCH,
	ITEMDESC_SYSMODULE_FM_ROBOT,

	ITEMDESC_SYSMODULE_FM_WIKI,		// 310
	ITEMDESC_SYSMODULE_FM_OFFLINESHOP,	
	ITEMDESC_SYSMODULE_FM_BORADCAST, // 完美服务
	ITEMDESC_SYSMODULE_FM_MATCHSYS,
	ITEMDESC_SYSMODULE_FM_ADDEXP,


	CMDDESC_TWO_KISS,				// 亲亲密密  315
	ITEMDESC_GENERALCARD_RANK,
	ITEMDESC_LEADERSHIP,
	ITEMDESC_GENERALCARD_MAXLEVEL,
	ITEMDESC_GENERALCARD_LEVEL,

	ITEMDESC_GENERALCARD_REINCARNATION_COUNT,
	ITEMDESC_VIGOUR,
	ITEMDESC_GENERALCARD_EXP_CANGIVE,
	ITEMDESC_GENERALCARD_SHOWORDER,
	ITEMDESC_GENERALCARD_SUITE_PROPRADIO,

	CMDDESC_JUMP_TRICK,
	CMDDESC_RUN_TRICK,
	ITEMDESC_GENERALCARD_EXP,
	ITEMDESC_GENERALCARD_TYPE1,
	ITEMDESC_GENERALCARD_TYPE2,

	ITEMDESC_GENERALCARD_TYPE3,
	ITEMDESC_GENERALCARD_TYPE4,
	ITEMDESC_GENERALCARD_TYPE5,
	ITEMDESC_GENERALCARD_TYPE6,
	ITEMDESC_CURRENT_PROFESSION,
	
	ITEMDESC_SYSMODULE_FM_AUTOHPMP, // 335
	ITEMDESC_FLYSWORD_NOIMPROVED,
	ITEMDESC_FLYSWORD_IMPROVE,
	ITEMDESC_VISIT_HTTP_WITH_TOKEN,
	ITEMDESC_OBOROKNIFE_WEAPON,

	ITEMDESC_SICKLE_WEAPON,			//	340
	ITEMDESC_ADDRIDEONPETSPEED,
};

///////////////////////////////////////////////////////////////////////////
//	
//	Types and Global variables
//	
///////////////////////////////////////////////////////////////////////////


///////////////////////////////////////////////////////////////////////////
//	
//	Declare of Global functions
//	
///////////////////////////////////////////////////////////////////////////


///////////////////////////////////////////////////////////////////////////
//	
//	Inline functions
//	
///////////////////////////////////////////////////////////////////////////

