/*
 * FILE: DlgAutoSliderBound.h
 *
 * DESCRIPTION: 
 *
 * CREATED BY: Liyi, 2005/12/2
 *
 * HISTORY: 
 *
 * Copyright (c) 2004 Archosaur Studio, All Rights Reserved.
 */

#ifndef _DLG_AUTO_SLIDER_BOUND_H_
#define _DLG_AUTO_SLIDER_BOUND_H_

//基本地形
#define MAX_HEIGHT 800 
#define MIN_HEIGHT 0

#define MAX_MAINSMOOTH 10
#define MIN_MAINSMOOTH 1

#define MAX_PARTSMOOTH 10
#define MIN_PARTSMOOTH 0

#define MAX_SEED 100
#define MIN_SEED 0

//纹理设置

#define MAX_TEXTURE_RATIO 200
#define MIN_TEXTURE_RATIO 0

#define MAX_MAIN_TEXTURE 100
#define MIN_MAIN_TEXTURE 0

#define MAX_PATCH_TEXTURE 400
#define MIN_PATCH_TEXTURE 0

#define MAX_PATCH_DIVISION 101
#define MIN_PATCH_DIVISION 2

//山脉
#define MAX_HEIGHT_HILL 800
#define MIN_HEIGHT_HILL 0

#define MAX_MAIM_SMOOTH_HILL 1000
#define MIN_MAIN_SMOOTH_HILL 100

#define MAX_PART_SMOOTH_HILL 100
#define MIN_PART_SMOOTH_HILL 0

#define MAX_TERRAIN_SEED_HILL 100
#define MIN_TERRAIN_SEED_HILL 0

#define MAX_BRIDGE_SCOPE 100
#define MIN_BRIDGE_SCOPE 0

#define MAX_BRIDGE_DEPTH 100
#define MIN_BRIDGE_DEPTH 0

#define MAX_BORDER_ERODE 100
#define MIN_BORDER_ERODE 0

#define MAX_LINE_HILL_WIDTH 200
#define MIN_LINE_HILL_WIDTH 1

//局部纹理

#define MAX_BORDER_SCOPE_LOCAL_TEX 100
#define MIN_BORDER_SCOPE_LOCAL_TEX 0

#define MAX_SEED_LOCAL_TEX 100
#define MIN_SEED_LOCAL_TEX 0

#define MAX_RADIO_LOCAL_TEX 2
#define MIN_RADIO_LOCAL_TEX 0

//路


#define MAX_ROAD_HEIGHT 20
#define MIN_ROAD_HEIGHT 5

#define MAX_MAIN_SMOOTH_ROAD 91
#define MIN_MAIN_SMOOTH_ROAD 1

#define MAX_PART_SMOOTH_ROAD 100
#define MIN_PART_SMOOTH_ROAD 0

#define MAX_ROAD_WIDTH 30
#define MIN_ROAD_WIDTH 10

#define MAX_SEED_ROAD 100
#define MIN_SEED_ROAD 0

//纹理数据

#define MAX_TEXTURE_U 50
#define MIN_TEXTURE_U 5

#define MAX_TEXTURE_V 50
#define MIN_TEXTURE_V 5

//摄像机
#define MAX_CAMERA_SPEED 450
#define MIN_CAMERA_SPEED 1

#endif