//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by TaskTemplEditor.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_TASKTEMPLEDITOR_FORM        101
#define IDD_SEL_STRING                  102
#define IDR_MAINFRAME                   128
#define IDR_TASKTETYPE                  129
#define IDD_TASK_PROPERTY               130
#define IDD_TASK_PREMISE                131
#define IDD_TASK_METHOD                 132
#define IDD_TASK_AWARD                  133
#define IDR_TASK_TEMPL                  134
#define IDD_NEW_TASK                    138
#define IDD_DIALOG_OPTION_VSS           140
#define IDB_LISTTAG                     142
#define IDD_TEMPL_ID_SEL                142
#define IDD_DIALOG_LOGO                 144
#define IDD_TASK_ID_SEL                 145
#define IDD_ITEMS_WANTED                146
#define IDD_NUMBER                      147
#define IDD_TEAM_INFO                   148
#define IDD_MEM_INFO                    149
#define IDD_DIALOG_CREATE_WINDOW        150
#define IDD_TIMETABLE                   151
#define IDD_TIMESPAN                    152
#define IDR_MENU_TALK                   152
#define IDB_TALKLIST                    153
#define IDD_OCCUPATION                  154
#define IDD_AWARD                       156
#define IDD_AWARD_BY_RATIO              157
#define IDD_AWARD_BY_ITEMS              158
#define IDD_TALK_DIALOG                 159
#define IDD_NEW_TALK_FILE               160
#define IDD_ITEMS_CAND                  161
#define IDD_FLOAT                       163
#define IDD_VECTOR                      164
#define IDD_PRETASK                     165
#define IDD_FIND_TASK                   166
#define IDD_VERIFY                      168
#define IDD_TASK_CLASS_FORM             169
#define IDD_MONSTER_WANTED              170
#define IDD_MONSTER                     171
#define IDR_TASK_CLASS                  172
#define IDD_TASK_LINK                   173
#define IDR_TASK_LINK                   174
#define IDD_PROFICIENCY                 175
#define IDD_AREA                        176
#define IDD_NPC_INFO                    180
#define IDD_SET_NPC_INFO                181
#define IDD_WEEK_SEL                    182
#define IDD_DATE_TYPE                   183
#define IDD_AWARD_CHANGE_VALUE          185
#define IDD_AWARD_DISPLAY_VALUE         186
#define IDD_DISPLAY_GLOBAL_VALUE        187
#define IDD_AWARD_MONSTER_SUMMONED      188
#define IDD_ABS_TIME                    189
#define IDD_COPY_SUB_TASK               190
#define IDD_ITEMS_SELECT                191
#define IDD_PQ_GLOBAL_VALUE             192
#define IDD_PQ_SUBTASK_PROP             193
#define IDD_PQ_AWARD_RANKING            194
#define IDD_RANKING_AWARD_EDIT          195
#define IDD_TASKREGION                  196
#define IDD_REGIONPOINT                 197
#define IDD_PLAYER_WANTED               198
#define IDD_PLAYER                      199
#define IDD_PLAYER_REQUIREMENT          200
#define IDD_PREM_TITLE                  201
#define IDC_TASK_TREE                   1001
#define IDC_TASK_TEMPL_CLASS            1002
#define IDC_APPLY                       1004
#define IDC_CANCEL                      1005
#define IDC_APPLY_CLASS                 1006
#define IDC_TASK_NAME                   1008
#define IDC_LIST_STRINGTABLE            1008
#define IDC_TIME_LIMIT                  1010
#define IDC_EDIT_NAME                   1010
#define IDC_USER                        1011
#define IDC_EDIT_WINDOW_ID              1011
#define IDC_EDIT1                       1011
#define IDC_PWD                         1012
#define IDC_DELV_YES_TEXT               1012
#define IDC_EDIT_NEW_NAME               1012
#define IDC_EDIT2                       1012
#define IDC_PQ_SPECIFY_TASK_CONTRIB     1012
#define IDC_DELIVERYSKILLLEVEL          1012
#define IDC_EDIT_Y                      1012
#define IDC_MAXLEVEL                    1012
#define IDC_EDIT_HISTORYHIGH            1012
#define IDC_MAX_TIME                    1013
#define IDC_VSS_PATH                    1013
#define IDC_UNFINISHED_NPC_TEXT         1013
#define IDC_EDIT3                       1013
#define IDC_PQ_CONTRIB                  1013
#define IDC_EDIT_Z                      1013
#define IDC_CARDCOUNT                   1013
#define IDC_CAN_REDO                    1014
#define IDC_UNFINISHED_PLAYER_TEXT      1014
#define IDC_EDIT4                       1014
#define IDC_PQ_RANDOM_CONTRIB           1014
#define IDC_EDIT_Y2                     1014
#define IDC_CARDRANKCOUNT               1014
#define IDC_IS_SPOUSE                   1015
#define IDC_DELV_NO_TEXT                1015
#define IDC_ENTER_WORLD_ID              1015
#define IDC_EDIT5                       1015
#define IDC_PQ_LOWEST_CONTRIB           1015
#define IDC_EDIT_Z2                     1015
#define IDC_PREMISE_LEVEL_MIN           1016
#define IDC_TREE_TEMPL                  1016
#define IDC_LEAVE_WORLD_ID              1016
#define IDC_ITEM_NUM                    1016
#define IDC_IS_TEAM                     1017
#define IDC_OFFLINE_FAIL_TIME           1017
#define IDC_ITEM_PERIOD                 1017
#define IDC_IS_CLAN                     1018
#define IDC_FINISH_NPC_TEXT             1018
#define IDC_TFT_DIRECT                  1019
#define IDC_FINISH_PLAYER_TEXT          1019
#define IDC_PREMISE_RMB_MIN             1019
#define IDC_TFT_NPC                     1020
#define IDC_IS_KU_TASK                  1020
#define IDC_TFT_CONFIRM                 1021
#define IDC_PREMISE_REINCARNATION_MIN   1021
#define IDC_IS_UNIQUE_STORAGE_TASK      1022
#define IDC_PREMISE_REINCARNATIONLEVEL_MIN 1023
#define IDC_CAN_REDO_AFTER_FAILURE      1032
#define IDC_TMK_KILL_CERTAIN_MONSTER    1033
#define IDC_TM_KILL_NUM_MONSTER         1034
#define IDC_TM_KILL_NUM_MONSTER2        1035
#define IDC_TM_COLLECT_NUM_ARTICLE      1036
#define IDC_TM_COLLECT_ARTICLE          1037
#define IDC_TM_CHECK_TRANSFORM          1037
#define IDC_TM_TALK_TO_NPC              1038
#define IDC_TM_REACH_SITE               1039
#define IDC_TM_WAIT_TIME                1040
#define IDC_TM_ANSWER_QUESTION          1041
#define IDC_TM_TINY_GAME                1042
#define IDC_TMK_NONE                    1043
#define IDC_MONSTER_TEMPL               1044
#define IDC_TM_GLOBAL_VAL_OK            1044
#define IDC_MONSTER_NUM                 1045
#define IDC_TM_LEAVE_SITE               1045
#define IDC_GOLD_NUM                    1046
#define IDC_TM_TREASH_HUNT              1046
#define IDC_ARTICLE_TEMPL               1047
#define IDC_TM_CHECK_LEVEL              1047
#define IDC_ARTICLE_NUM                 1048
#define IDC_NPC_TALKTO                  1049
#define IDC_NPC_TO_KILL                 1050
#define IDC_NEED_RECORD                 1051
#define IDC_AWARD_SUCCESS               1052
#define IDC_CHECK_AUTO_UPDATE           1052
#define IDC_AWARD_FAILURE               1053
#define IDC_MAX_RECEIVER                1054
#define IDC_RECEIVER_NUM                1055
#define IDC_PREMISE_DEPOSIT             1056
#define IDC_TREE_TALK                   1056
#define IDC_PREMISE_REPUTATION          1057
#define IDC_RADIO_TALK_TYPE1            1057
#define IDC_PREMISE_COTASK              1058
#define IDC_RADIO_TALK_TYPE2            1058
#define IDC_COMBO_SERVICE               1059
#define IDC_PREMISE_FACTION_CONTRIB     1059
#define IDC_TM_KILL_NPC                 1060
#define IDC_EDIT_WINDOW_DESC            1060
#define IDC_PREMISE_NEED_RECORD_TASKS_NUM 1060
#define IDC_TM_PROTECT_NPC              1061
#define IDC_EDIT_TALK_NAME              1061
#define IDC_RADIO_TALK_TYPE3            1061
#define IDC_PREM_FORCE_CONTRIB          1061
#define IDC_TM_NPC_REACH_SITE           1062
#define IDC_EDIT_TALK_ID                1062
#define IDC_PREM_FORCE_REPU             1062
#define IDC_KILLED_AS_FAIL              1063
#define IDC_BUTTON_TALK_TEST            1063
#define IDC_PREM_FORCE_EXP              1063
#define IDC_STATIC_WINDOW               1064
#define IDC_PREM_FORCE_SP               1064
#define IDC_STATIC_ID                   1065
#define IDC_PREMISE_TITLE_REQUIRED      1065
#define IDC_STATIC_DESC                 1066
#define IDC_STATIC_SERVICE              1067
#define IDC_PREMISE_HAS_COTASK          1068
#define IDC_STATIC_SERVICE_TYPE         1068
#define IDC_ORDER_EXE_CHILD             1069
#define IDC_BUTTON_DELETE_ITEM          1069
#define IDC_STATIC_COMMAND              1069
#define IDC_BUTTON_MOVE_ITEM_UP         1070
#define IDC_EDIT_COMMAND_NAME           1070
#define IDC_PARENT_ALSO_FAIL            1071
#define IDC_BUTTON_MOVE_ITEM_DOWN       1071
#define IDC_STATIC_SERVICE_TYPE2        1071
#define IDC_STATIC_SERVICE_PARAMS       1072
#define IDC_CAN_GIVEUP                  1073
#define IDC_STATIC_WINDOW2              1073
#define IDC_BUTTON_SERVICE_LINK         1075
#define IDC_SEL_TASK1                   1076
#define IDC_EDIT_SERVICE_LINK           1076
#define IDC_PROTECT_TIME                1077
#define IDC_SEL_TASK_ITEM               1077
#define IDC_SEL_COTASK                  1078
#define IDC_SEL_TASK2                   1079
#define IDC_SEL_MUTEX_TASK              1079
#define IDC_NEW_TASK                    1080
#define IDC_SEL_TASK3                   1080
#define IDC_SEL_NEW_TASK                1081
#define IDC_SEL_TASK4                   1081
#define IDC_SP_NUM                      1082
#define IDC_SEL_TASK5                   1082
#define IDC_COMBO_SERVICE_PARAMS        1082
#define IDC_REPU_NUM                    1083
#define IDC_EXP_NUM                     1084
#define IDC_RACE                        1085
#define IDC_AWARD_CHANGE_VALUE          1085
#define IDC_PARENT_ALSO_SUCCESS         1086
#define IDC_AWARD_DISPLAY_VALUE         1086
#define IDC_AWARD_DISPLAY_STRING        1087
#define IDC_ENTER_REGION_FAIL           1087
#define IDC_AW_FACTION_CONTRIB          1087
#define IDC_PREMISE_LEVEL_MAX           1088
#define IDC_LEAVE_REGION_FAIL           1088
#define IDC_AW_FACTION_EXP_CONTRIB      1088
#define IDC_GIVEUP_CLEAR                1089
#define IDC_PREMISE_RMB_MAX             1089
#define IDC_OFFLINE_FAIL                1090
#define IDC_PREMISE_REINCARNATION_MAX   1090
#define IDC_PREM_TASK_LIST              1091
#define IDC_TASK_FAIL_TIME              1091
#define IDC_PREMISE_REINCARNATIONLEVEL_MAX 1091
#define IDC_ITEM_NOT_TAKE_OFF           1092
#define IDC_OCCUPATION                  1093
#define IDC_LEAVEFORCE_FAIL             1093
#define IDC_NAME                        1094
#define IDC_LEAVEFACTION_FAIL           1094
#define IDC_TASK_ITEM                   1095
#define IDC_PREM_TASK1                  1096
#define IDC_SEL_MONSTER                 1097
#define IDC_PREM_TASK2                  1097
#define IDC_SEL_ARTICLE                 1098
#define IDC_TREE_TASK                   1098
#define IDC_PREM_TASK3                  1098
#define IDC_SEL_NPC_TALKTO              1099
#define IDC_PREM_TASK4                  1099
#define IDC_SEL_NPC_TO_KILL             1100
#define IDC_PREM_TASK5                  1100
#define IDC_NPC_TO_PROTECT              1101
#define IDC_SEL_NPC_TO_PROTECT          1102
#define IDC_NPC_MOVING                  1103
#define IDC_SEL_NPC_MOVING              1104
#define IDC_WAITTIME_LEN                1105
#define IDC_SHOW_TASKCHAR               1106
#define IDC_ZONE_START_X                1107
#define IDC_ZONE_START_Z                1108
#define IDC_ZONE_SIDE                   1109
#define IDC_ZONES_NUM_X                 1110
#define IDC_ZONES_NUM_Z                 1111
#define IDC_DESCRIPT                    1114
#define IDC_TRIBUTE                     1115
#define IDC_ITEMS_WANTED                1124
#define IDC_EDIT_ITEMS_WANTED           1125
#define IDC_EDIT_TEAM                   1126
#define IDC_EDIT_OCCUP                  1127
#define IDC_PREM1_COMPARE1              1128
#define IDC_ADD                         1129
#define IDC_PREM1_COMPARE               1129
#define IDC_DEL                         1130
#define IDC_DELETE                      1130
#define IDC_PREM1_COMPARE2              1130
#define IDC_ITEMS                       1131
#define IDC_EDIT                        1131
#define IDC_PREM2_COMPARE1              1131
#define IDC_ADD2                        1131
#define IDC_NUM                         1132
#define IDC_PREM2_COMPARE               1132
#define IDC_DEL2                        1132
#define IDC_PREM2_COMPARE2              1133
#define IDC_PREM_AND_OR                 1134
#define IDC_EDIT_NUM                    1137
#define IDC_SRC                         1138
#define IDC_SEL_SRC                     1139
#define IDC_DROP_ITEM                   1142
#define IDC_DROP_PROB                   1145
#define IDC_DPH                         1146
#define IDC_TEAM_RCV                    1147
#define IDC_DPS                         1147
#define IDC_SHARE_TASK                  1148
#define IDC_SHARE_ACQUIRED              1149
#define IDC_ALL_FAIL                    1150
#define IDC_CAPTAIN_FAIL                1151
#define IDC_DISMISS_SELF_FAIL           1152
#define IDC_ALL_SUCCESS                 1153
#define IDC_MEM_LIST                    1154
#define IDC_DISTINGUISHED_OCC           1155
#define IDC_GENDER                      1159
#define IDC_LEV_MIN                     1160
#define IDC_FACTION_ROLE                1160
#define IDC_LEV_MAX                     1161
#define IDC_GENERALCARD_RANK            1161
#define IDC_MEM_MIN                     1162
#define IDC_MEM_MAX                     1163
#define IDC_MEM_TASK                    1164
#define IDC_SEL_MEM_TASK                1165
#define IDC_TIMETALBE                   1166
#define IDC_TEAM_FORCE                  1166
#define IDC_START_HOUR                  1169
#define IDC_END_HOUR                    1170
#define IDC_START_MIN                   1171
#define IDC_END_MIN                     1172
#define IDC_EDIT_TIMETABLE              1172
#define IDC_OCCUPATIONS                 1175
#define IDC_COMMON                      1180
#define IDC_BY_EACH                     1182
#define IDC_BY_TM_RATIO                 1184
#define IDC_BY_ITEMS                    1185
#define IDC_AWARD                       1188
#define IDC_EDIT_AWARD                  1192
#define IDC_EDIT_RATIO                  1193
#define IDC_ITEM                        1194
#define IDC_EDIT_ITEM                   1195
#define IDC_CHECK_TEAMMATE              1196
#define IDC_DIST                        1197
#define IDC_DELIVER_PREM_ITEM           1198
#define IDC_DELIVER_TALK                1199
#define IDC_DELIVER_ITEM_TALK           1201
#define IDC_ITEMS_CAND                  1201
#define IDC_ACCEPTED_TALK               1202
#define IDC_AWARD_TALK                  1203
#define IDC_PROB                        1205
#define IDC_CHOOSE_ONE                  1207
#define IDC_HAS_ZONE                    1208
#define IDC_SEL_MIN_POINT               1209
#define IDC_SEL_MAX_POINT               1210
#define IDC_SEL_MIN_POINT2              1211
#define IDC_Y                           1212
#define IDC_SEL_MAX_POINT2              1212
#define IDC_Z                           1213
#define IDC_X                           1214
#define IDC_RCV_CHCK_MEM                1215
#define IDC_CNT_BY_MEM                  1216
#define IDC_RCV_MEM_DIST                1217
#define IDC_CNT_BY_MEM_DIST             1218
#define IDC_TASK_ID                     1219
#define IDC_SHOW_BY_LEVEL               1220
#define IDC_SHOW_BY_ITEMS               1221
#define IDC_PRETASK                     1221
#define IDC_SHOW_BY_DEPOSIT             1222
#define IDC_SHOW_BY_REPUTATION          1223
#define IDC_SHOW_BY_PRE_TASK            1224
#define IDC_SHOW_BY_TEAM                1225
#define IDC_SHOW_BY_GENDER              1226
#define IDC_SHOW_BY_OCCUP               1227
#define IDC_SEL_PRETASK                 1228
#define IDC_SHOW_BY_PERIOD              1229
#define IDC_SHOW_TALK                   1229
#define IDC_SHOW_BY_SPOUSE              1230
#define IDC_AUTO_DELV                   1230
#define IDC_SHOW_BY_FACTION             1231
#define IDC_RAND_ONE                    1231
#define IDC_COTASK_COND1                1232
#define IDC_RAND_ONE2                   1232
#define IDC_DISAPPEAR                   1232
#define IDC_COTASK_COND2                1233
#define IDC_WHETHER_PROMPT              1233
#define IDC_CAP_SUCCESS                 1234
#define IDC_SHOW_BY_RMB                 1234
#define IDC_SUCCESS_DIST                1235
#define IDC_SHOW_BY_FACTION_CONTRIB     1235
#define IDC_DEATH_TRIG                  1236
#define IDC_SHOW_BY_NEEDRECORD_TASKS_NUM 1236
#define IDC_SHOW_BY_TRANSFORMED         1237
#define IDC_TASK                        1238
#define IDC_SHOW_BY_FORCE               1238
#define IDC_CLEAR_ACQUIRED              1239
#define IDC_SHOW_BY_FORCE_CONTRIB       1239
#define IDC_PERIOD                      1240
#define IDC_NOT_CLEAR_WHEN_FAILED       1240
#define IDC_AWARD_NUM_TYPE              1241
#define IDC_TRANSFORMED                 1241
#define IDC_AWARD_DEATH_TYPE            1242
#define IDC_PREM_FORCE                  1242
#define IDC_SHOW_BY_FORCE_REPU          1243
#define IDC_SHOW_BY_FORCE_EXP           1244
#define IDC_REPORT                      1245
#define IDC_SHOW_BY_FORCE_SP            1245
#define IDC_NO_DELIVER_TALK             1246
#define IDC_CHECK_FORCE                 1246
#define IDC_DUP_MONSTER                 1247
#define IDC_PREM_FORCE_AL               1247
#define IDC_KEY_TASK                    1248
#define IDC_SHOW_BY_FORCE_AL            1248
#define IDC_SHOW_PROMPT                 1249
#define IDC_SHOW_BY_WEDDING_OWNER       1249
#define IDC_SUIT_LEVEL                  1250
#define IDC_SHOW_BY_KING                1250
#define IDC_SWITCH_SCENE_FAIL           1251
#define IDC_SHOW_BY_NOT_IN_TEAM         1251
#define IDC_DELV_NPC_TEXT               1252
#define IDC_HIDDEN                      1252
#define IDC_SHOW_BY_TITLE               1252
#define IDC_SEL_TITLE                   1253
#define IDC_NOT_ADD_COUNT_WHEN_FAILED   1253
#define IDC_CHECK_HISTORY_MAX_LEVEL     1254
#define IDC_SHOW_BY_REINCARNATION       1255
#define IDC_PREM_CHECK_REINCARNATION    1256
#define IDC_SHOW_BY_REINCARNATIONLEVEL  1257
#define IDC_PREM_CHECK_REINCARNATIONLEVEL 1258
#define IDC_LEVEL_MIN                   1259
#define IDC_PREM_CHECK_REALMEXP_FULL    1259
#define IDC_LEVEL_MAX                   1260
#define IDC_EDIT_MONSTER                1280
#define IDC_MONSTERS                    1281
#define IDC_DROP_NUM                    1285
#define IDC_SEL_ITEM                    1287
#define IDC_MONSTER                     1288
#define IDC_TASK_LINK                   1290
#define IDC_NEW_LINK                    1291
#define IDC_NEXT_NAME                   1292
#define IDC_PREV                        1293
#define IDC_NEXT                        1294
#define IDC_PREV_NAME                   1295
#define IDC_DELV_NPC                    1296
#define IDC_SEL_DELV_NPC                1297
#define IDC_AWARD_NPC                   1298
#define IDC_SEL_AWARD_NPC               1299
#define IDC_FIND                        1299
#define IDC_TO_FIND                     1300
#define IDC_CHANGE_PROFICIENCY          1307
#define IDC_SKILL1                      1308
#define IDC_SKILL2                      1309
#define IDC_SKILL3                      1310
#define IDC_SKILL4                      1311
#define IDC_PROFICIENCY1                1312
#define IDC_PROFICIENCY2                1313
#define IDC_SKILL_TASK                  1313
#define IDC_PROFICIENCY3                1314
#define IDC_STATION                     1314
#define IDC_PROFICIENCY4                1315
#define IDC_WRONG_NPC                   1315
#define IDC_EDIT_GIVEN_ITEMS            1318
#define IDC_START_DATE                  1319
#define IDC_END_DATE                    1320
#define IDC_PLAYER_LEV                  1320
#define IDC_LIST1                       1321
#define IDC_WORD_ID                     1322
#define IDC_NO_USE                      1323
#define IDC_TEST                        1324
#define IDC_STOREHOUSE                  1325
#define IDC_FURY                        1326
#define IDC_TRANSPORT                   1327
#define IDC_STOREHOUSE2                 1327
#define IDC_TRANS_POINT                 1328
#define IDC_FORCE_ACTIVITY              1328
#define IDC_TRANS_WORLD                 1329
#define IDC_STOREHOUSE3                 1329
#define IDC_TRANS_WLD                   1330
#define IDC_EDIT_CHANGE_VAL             1330
#define IDC_TRANS_PT                    1331
#define IDC_EDIT_ENTER_SMALL            1331
#define IDC_GOLD_WANTED                 1332
#define IDC_AWARD_NUM_VAL               1332
#define IDC_EDIT_ENTER_BIG              1332
#define IDC_EDIT_LEAVE_SMALL            1333
#define IDC_STOREHOUSE4                 1333
#define IDC_FACTION_CONTRIB_WANTED      1333
#define IDC_SITE_ID                     1334
#define IDC_EDIT_LEAVE_BIG              1334
#define IDC_FORCE_CONTRIB               1334
#define IDC_PRE_TASK                    1335
#define IDC_EDIT_FAIL_TIME              1335
#define IDC_SITE_ID2                    1335
#define IDC_FORCE_REPU                  1335
#define IDC_TOTAL_PROB                  1336
#define IDC_FACTION_EXP_CONTRIB_WANTED  1336
#define IDC_FORCE_SET_REPU              1336
#define IDC_SIGNATURE                   1337
#define IDC_TASKLIMIT                   1337
#define IDC_AWARD_TITLE                 1337
#define IDC_REACH_LEVEL                 1337
#define IDC_TYPE                        1338
#define IDC_REACH_REINCARNATION         1338
#define IDC_TEAM                        1339
#define IDC_REACH_REINCARNATIONLEVEL    1339
#define IDC_SPECIAL_AWARD               1340
#define IDC_NPC                         1341
#define IDC_UNMATCH                     1344
#define IDC_NPC_TO_FIND                 1345
#define IDC_FIND_NPC                    1346
#define IDC_SEEK_OUT                    1347
#define IDC_PET_NUM                     1349
#define IDC_AUTO_DELIVER                1350
#define IDC_SHOW_DIRECTION              1351
#define IDC_WEEK_1                      1353
#define IDC_WEEK_2                      1354
#define IDC_WEEK_3                      1355
#define IDC_WEEK_4                      1356
#define IDC_WEEK_5                      1357
#define IDC_WEEK_6                      1358
#define IDC_WEEK_7                      1359
#define IDC_DATE_TYPE                   1361
#define IDC_MONTH_TYPE                  1362
#define IDC_WEEK_TYPE                   1363
#define IDC_DAY_TYPE                    1364
#define IDC_TYPE_1                      1365
#define IDC_TYPE_2                      1366
#define IDC_TYPE_3                      1367
#define IDC_TYPE_4                      1368
#define IDC_MONTH_DAY_START             1369
#define IDC_MONTH_DAY_END               1370
#define IDC_WEEK_DAY_START              1371
#define IDC_WEEK_DAY_END                1372
#define IDC_IS_GM                       1372
#define IDC_CONTROLLER                  1373
#define IDC_PREM_NEED_COMP              1373
#define IDC_TYPE_5                      1373
#define IDC_IS_SHIELD_USER              1374
#define IDC_YEAR_START_MONTH            1374
#define IDC_YEAR_END_MONTH              1375
#define IDC_TRIG_CTRL                   1376
#define IDC_YEAR_START_DAY              1376
#define IDC_YEAR_END_DAY                1377
#define IDC_ABS_TIME                    1378
#define IDC_AVAIL_FREQUENCY             1379
#define IDC_INVENTORY                   1380
#define IDC_PREMISE_REPUMAX             1381
#define IDC_USE_LEV_CO                  1382
#define IDC_PREM1_KV1                   1382
#define IDC_MARRIAGE                    1383
#define IDC_PREM1_KV2                   1383
#define IDC_AWARD_NEED_MULTI            1383
#define IDC_DIVORCE                     1384
#define IDC_CHECK_CHANGE_VAL            1384
#define IDC_PREM2_KV1                   1384
#define IDC_TITLE                       1384
#define IDC_SEND_MSG                    1385
#define IDC_PREM2_KV2                   1385
#define IDC_TOKENSHOP                   1385
#define IDC_MSG_CHANNEL                 1386
#define IDC_WEDDING_OWNER               1386
#define IDC_FIN_NEED_COMP               1387
#define IDC_AWARD_DEATH                 1387
#define IDC_IS_KING                     1387
#define IDC_FIN1_COMPARE1               1388
#define IDC_NOT_IN_TEAM                 1388
#define IDC_FIN1_KV1                    1389
#define IDC_FIN1_COMPARE                1390
#define IDC_FIN1_COMPARE2               1391
#define IDC_FIN1_KV2                    1392
#define IDC_FIN_AND_OR                  1393
#define IDC_FIN2_COMPARE1               1394
#define IDC_FIN2_KV1                    1395
#define IDC_FIN2_COMPARE                1396
#define IDC_FIN2_COMPARE2               1397
#define IDC_FIN2_KV2                    1398
#define IDC_DISPLAY_STRING              1399
#define IDC_DISPLAY_VALUE               1400
#define IDC_AWARD_CALL_MONSTER          1401
#define IDC_AWARD_SUMMON_MONSTER        1401
#define IDC_RAND_SEL                    1402
#define IDC_RADIUS                      1403
#define IDC_JUST_CHECK                  1405
#define IDC_ABS_DATE                    1406
#define IDC_EDIT_HOUR                   1407
#define IDC_EDIT_MINUTE                 1408
#define IDC_COPY_SUB_TASK               1408
#define IDC_TREE_SUB_TASK               1410
#define IDC_CHECK_COPY_SUB_TASK         1412
#define IDC_STATIC_OLD_NAME             1413
#define IDC_SELECT_ITEMS                1414
#define ID_ADD                          1415
#define ID_DEL                          1416
#define ID_DEL2                         1417
#define IDC_PQ_TASK                     1419
#define IDC_PQ_VALUE                    1420
#define IDC_PQ_SUB_TASK                 1421
#define IDC_PQ_SUB_TASK_PROP            1422
#define IDC_LIST3                       1425
#define IDC_PQ_DISPLAY_VALUE            1425
#define IDC_MONSTER_CONTRIB             1428
#define IDC_CLEAR_CONTRIB               1429
#define IDC_PQ_RANKING                  1433
#define IDC_RANKING_LIST                1434
#define IDC_AWARD_BY_PROF               1435
#define IDC_BUTTON_ADD                  1436
#define IDC_BUTTON_DEL                  1437
#define IDC_BUTTON_EDIT                 1438
#define IDC_RANK_START                  1440
#define IDC_RANK_END                    1441
#define IDC_AWARD_ITEM                  1442
#define IDC_PQ_SPECIFY_TASKID           1443
#define IDC_ACCOUNT_TASK_LIMIT          1444
#define IDC_ACCOUNT_TASK_LIMIT_CNT      1445
#define IDC_ROLE_TASK_LIMIT             1445
#define IDC_DIVIDEND                    1446
#define IDC_TASK_PERIOD_LIMIT           1446
#define IDC_CHARACTER_TIME              1447
#define IDC_CHAR_TIME                   1447
#define IDC_CHECK2                      1448
#define IDC_SHOW_BY_CHAR_TIME           1448
#define IDC_CHK_FAIRY                   1448
#define IDC_CHARACTER_START_TIME        1449
#define IDC_CHAR_START_TIME             1449
#define IDC_CHAR_CURR_TIME              1450
#define IDC_CHAR_SPECIFY_TIME           1451
#define IDC_CHAR_CURR_TIME2             1451
#define IDC_CHAR_TIME_GREATER_THAN      1452
#define IDC_SPECIFIED_DATE              1453
#define IDC_COUPLE_ONLY                 1454
#define IDC_PQ_SPECIFY_SUBTASKID        1455
#define IDC_CHAR_PROBABILITY            1455
#define IDC_AWARD_DELIVERYSKILL         1456
#define IDC_WORLD_CONTRIB_REQUIRE       1456
#define IDC_AWARDSKILLLEVEL             1457
#define IDC_AWARDSKILLID                1458
#define IDC_DELIVERYSKILL               1459
#define IDC_30_TASKLIMIT                1459
#define IDC_DELIVERYSKILLID             1460
#define IDC_REINCARNATIONLEVEL_EXP      1460
#define IDC_SHOWGFX                     1461
#define IDC_REINCARNATIONLEVEL_MAX      1461
#define IDC_AWARD_EXPAND_REALMLEVEL_MAX 1461
#define IDC_CHANGE_PQRANK               1462
#define IDC_LEADERSHIP                  1462
#define IDC_BTN_ADD                     1463
#define IDC_AWARD_WORLD_CONTRIB         1463
#define IDC_BTN_DEL                     1464
#define IDC_LST_REGION                  1465
#define IDC_EDIT_X                      1466
#define IDC_EDIT_X2                     1467
#define IDC_CHK_COMPAREITEMANDINVENTORY 1468
#define IDC_EDIT_INVENTORYSLOTNUM       1469
#define IDC_LEAST_PREM_TASK_NUM         1471
#define IDC_PLAYERS                     1473
#define IDC_EDIT_PLAYER                 1474
#define IDC_PLAYER                      1475
#define IDC_SEL_PLAYER                  1476
#define IDC_PLAYER_NUM                  1477
#define IDC_WUXIA                       1477
#define IDC_JIANLING                    1478
#define IDC_CIKE                        1479
#define IDC_YULING                      1480
#define IDC_YAOSHOU                     1481
#define IDC_FASHI                       1482
#define IDC_MEILING                     1483
#define IDC_WUSHI                       1484
#define IDC_YUMANG                      1485
#define IDC_YAOJING                     1486
#define IDC_HUAGUANG                    1487
#define IDC_ANYIN                       1488
#define IDC_HUIYE                       1489
#define IDC_RADIO1                      1490
#define IDC_RADIO2                      1491
#define IDC_MINLEVEL                    1492
#define IDC_RADIO3                      1493
#define IDC_LST_TITLE                   1493
#define ID_PERIOD                       1494
#define IDC_BTN_EDITHISTORYVAR          1495
#define IDC_EDIT_HISTORYLOW             1496
#define IDC_RAD_SIMPLETASK              1497
#define IDC_CMB_EMOTION                 1498
#define IDC_CHK_CARDCOUNT               1499
#define IDC_CHK_CARDRANKCOUNT           1500
#define IDC_CHK_SHOWPREMHISTORY         1501
#define IDC_CHK_SHADOW                  1502
#define IDC_RAD_NAVIGATE                1503
#define ID_ADD_SUB_TASK                 32771
#define ID_DEL_SUB_TASK                 32772
#define ID_INSERT_TASK                  32773
#define ID_CONFIG_VSS                   32774
#define ID_NEW_TASK                     32775
#define ID_CHECK_IN                     32776
#define ID_CHECK_OUT                    32777
#define ID_SAVE_TASK                    32778
#define ID_REFRESH                      32779
#define ID_SAVEALL                      32780
#define ID_EXPORT                       32781
#define ID_VIEW                         32782
#define ID_CREATE_TALK_WINDOW           32783
#define ID_UNDO                         32784
#define ID_MODIFY_TALK_WINDOW           32784
#define ID_FIND_TASK                    32784
#define ID_REDO                         32785
#define ID_TEST_PACK                    32785
#define ID_VERIFY                       32786
#define ID_EXPORT_DESCRIPT              32787
#define ID_CLASS_MODE                   32788
#define ID_ADD_CLASS_TEMPL              32789
#define ID_CHECK_IN_CLASS               32790
#define ID_CHECK_OUT_CLASS              32791
#define ID_TASK_LINK                    32792
#define ID_INSERT_LINK                  32793
#define ID_ADD_LINK                     32794
#define ID_DEL_LINK                     32795
#define ID_FIND_NAME                    32798
#define ID_FIND_NEXT                    32799
#define ID_FIND_BY_ID                   32801
#define ID_CHECK_NPC                    32802
#define ID_TEST_DYN_PACK                32803
#define ID_TEST_EXPORT_DYN              32805
#define ID_VIEW_NPC_INFO                32806
#define ID_EDIT_NPC_INFO                32807
#define ID_EXPORT_NPC_INFO              32808
#define ID_RECORD                       32809
#define IDD_LOAD_FORM_EXCEL             32810

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        202
#define _APS_NEXT_COMMAND_VALUE         32811
#define _APS_NEXT_CONTROL_VALUE         1504
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
