//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AudioEditor.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_MAIN_TOOLBAR                101
#define IDC_POINTER                     104
#define IDC_NODROP                      106
#define IDR_MAINFRAME                   128
#define IDR_AudioEditorTYPE             129
#define IDR_CONTEXT_MENU                130
#define IDR_POPUP_TOOLBAR               131
#define IDB_WORKSPACE                   147
#define IDB_TOOLBAR256                  151
#define IDD_CREATE_PROJECT              160
#define IDD_OPEN_PROJECT                161
#define IDD_EDIT_NAME                   162
#define IDD_PROP_SLIDER                 163
#define IDB_BTN_PLAY_UP                 165
#define IDB_BTN_PLAY_DOWN               166
#define IDB_BTN_STOP                    167
#define IDD_SELECT_AUDIO                168
#define IDD_SELECT_SOUNDDEF             169
#define IDI_ICON_BANK                   170
#define IDI_ICON_BANK_ARCHIVE           171
#define IDI_ICON_AUDIO                  172
#define IDI_ICON_SOUNDDEF               173
#define IDI_ICON_SOUNDDEF_ARCHIVE       174
#define IDI_ICON_EVENT_GROUP            177
#define IDI_ICON_EVENT                  178
#define IDB_BTN_UNCHECKED               180
#define IDB_BTN_CHECKED                 181
#define IDD_LAYER_PROP                  182
#define IDD_ADD_EFFECT                  183
#define IDD_EFFECT_PROP                 184
#define IDD_SET_PARAM_VALUE             185
#define IDD_PARAM_PROP                  186
#define IDD_SOUND_INS_PROP              187
#define IDC_CURSOR1                     191
#define IDC_HAND_CURSOR                 191
#define IDD_REVERB                      192
#define IDD_NEW_REVERB                  193
#define IDD_SET_VALUE                   194
#define IDC_MOVE_CURSOR                 195
#define IDC_CURSOR2                     196
#define IDC_RESIZE_CURSOR               196
#define IDD_CUR_PLAYING                 197
#define IDD_UPLOAD_RES                  198
#define IDD_DOWNLOAD_RES                199
#define IDD_EVENT_PROP                  200
#define IDD_SOUNDDEF_PROP_FRM           201
#define IDD_SLIDER                      202
#define IDD_SETTINGS                    203
#define IDB_BTN_PAUSE_UP                204
#define IDB_BTN_PAUSE_DOWN              205
#define IDD_SELECT_EVENT                206
#define IDC_COMPANY_URL                 1041
#define IDC_EDIT_PROJ_NAME              1042
#define IDC_LIST_PROJ_NAMES             1043
#define IDC_LIST_EFFECT                 1043
#define IDC_LIST_REVERB                 1043
#define IDC_LIST_PLAYING                1043
#define IDC_LIST_UPLOAD                 1043
#define IDC_LIST_DOWNLOAD_FOLDERS       1043
#define IDC_TREE_CTRL                   1044
#define IDC_EDIT_NAME                   1045
#define IDC_SLIDER                      1046
#define IDC_MIN                         1047
#define IDC_MAX                         1048
#define IDC_STEP                        1049
#define IDC_TREE_BANK                   1049
#define IDC_VAL                         1050
#define IDC_TREE_SOUNDDEF               1050
#define IDC_TIP                         1051
#define IDC_LAYER_NAME                  1051
#define IDC_PARAM_COMBO                 1052
#define IDC_PROP_FRAME                  1053
#define IDC_PARAM_VALUE                 1054
#define IDC_PARAM_NAME                  1055
#define IDC_MIN_VALUE                   1056
#define IDC_MAX_VALUE                   1057
#define IDC_EFFECT_TYPE                 1058
#define IDC_PROP_FRM                    1059
#define IDC_DEL_PROJECT                 1060
#define IDC_FRM_REVERB_PROP             1061
#define IDC_NEW_REVERB                  1062
#define IDC_DEL_REBERB                  1063
#define IDC_COMBO_REVERBS               1064
#define IDC_REVERB_SAVE                 1066
#define IDC_EDIT1                       1067
#define IDC_EDIT_VALUE                  1067
#define IDC_EDIT_UPLOAD_PATH            1067
#define IDC_PARAM_VEL                   1067
#define IDC_BTN_ADD_FILE                1068
#define IDC_EDIT_PARAM                  1068
#define ID_BTN_DOWNLOAD                 1069
#define IDC_EVENT_PROP_FRM              1070
#define IDC_SOUNDDEF_PROP_FRM           1071
#define IDC_COMBO_PARAM_LOOP_TYPE       1072
#define IDC_SLIDER_CTRL                 1073
#define IDC_STATIC_SLIDER_CTRL_MIN      1074
#define IDC_STATIC_SLIDER_CTRL_MAX      1075
#define IDC_STATIC_SLIDER_CTRL_CUR      1076
#define IDC_STATIC_SLIDER_CTRL_TIP      1077
#define IDC_STATIC_SLIDER_CTRL_STEP     1078
#define IDC_FRM_SETTING_PROP            1079
#define IDC_PARAM_SEEKSPEED             1081
#define IDC_TREE_EVENT                  1082
#define ID_VIEW_CUSTOMIZE               32770
#define ID_VIEW_TOOLBARS                32771
#define ID_VIEW_SOUNDDEF                32792
#define ID_VIEW_USER_TOOLBAR1           32793
#define ID_VIEW_USER_TOOLBAR2           32794
#define ID_VIEW_USER_TOOLBAR3           32795
#define ID_VIEW_USER_TOOLBAR4           32796
#define ID_VIEW_USER_TOOLBAR5           32797
#define ID_VIEW_USER_TOOLBAR6           32798
#define ID_VIEW_USER_TOOLBAR7           32799
#define ID_VIEW_USER_TOOLBAR8           32800
#define ID_VIEW_USER_TOOLBAR9           32801
#define ID_VIEW_USER_TOOLBAR10          32802
#define ID_VIEW_EVENT                   32803
#define ID_VIEW_OUTPUT                  32804
#define ID_VIEW_APPLOOK_2000            32826
#define ID_VIEW_APPLOOK_XP              32827
#define ID_VIEW_APPLOOK_2003            32828
#define ID_VIEW_APPLOOK_WIN_XP          32829
#define ID_VIEW_APPLOOK_VS2005          32830
#define ID_VIEW_APPLOOK_2007            32831
#define ID_VIEW_APPLOOK_2007_1          32832
#define ID_VIEW_APPLOOK_2007_2          32833
#define ID_VIEW_APPLOOK_2007_3          32834
#define ID_VIEW_APPLOOK_VS2008          32835
#define ID_VIEW_BANK                    32851
#define ID_VIEW_PROPERTY                32852
#define ID_MY_FILE_SAVE                 32855
#define ID_MY_FILE_SAVE_AS              32856
#define ID_32857                        32857
#define ID_REVERB_EDITOR                32858
#define ID_32859                        32859
#define ID_UPLOAD_RES                   32860
#define ID_32861                        32861
#define ID_DOWNLOAD_RES                 32862
#define ID_32863                        32863
#define ID_OPTIONS                      32864
#define ID_SETTINGS                     32865
#define ID_EXPORT_TEXT                  32866
#define ID_EXPORT_BINARY_PROJECT        32868

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        207
#define _APS_NEXT_COMMAND_VALUE         32869
#define _APS_NEXT_CONTROL_VALUE         1083
#define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
